### PR TITLE
Handle async call back to already destroyed UI

### LINKED ISSUE #1426: ChatController async binding call
Via GPlay Console:
```
java.lang.NullPointerException: 
  at com.nextcloud.talk.controllers.util.ControllerViewBindingDelegate.getValue (ControllerViewBindingDelegate.kt:47)
  at com.nextcloud.talk.controllers.ChatController.getBinding (ChatController.kt:197)
  at com.nextcloud.talk.controllers.ChatController.access$getBinding (ChatController.kt:185)
  at com.nextcloud.talk.controllers.ChatController$onViewBound$8.onTextChanged (ChatController.kt:612)
  at android.widget.TextView.sendOnTextChanged (TextView.java:9459)
  at android.widget.TextView.handleTextChanged (TextView.java:9536)
  at android.widget.TextView$ChangeWatcher.onTextChanged (TextView.java:12428)
  at android.text.SpannableStringBuilder.sendTextChanged (SpannableStringBuilder.java:1208)
  at android.text.SpannableStringBuilder.replace (SpannableStringBuilder.java:578)
  at androidx.emoji.widget.SpannableBuilder.replace (SpannableBuilder.java:312)
  at android.text.SpannableStringBuilder.replace (SpannableStringBuilder.java:509)
  at androidx.emoji.widget.SpannableBuilder.replace (SpannableBuilder.java:303)
  at androidx.emoji.widget.SpannableBuilder.replace (SpannableBuilder.java:51)
  at android.view.inputmethod.BaseInputConnection.replaceText (BaseInputConnection.java:850)
  at android.view.inputmethod.BaseInputConnection.commitText (BaseInputConnection.java:200)
  at com.android.internal.widget.EditableInputConnection.commitText (EditableInputConnection.java:183)
  at android.view.inputmethod.InputConnectionWrapper.commitText (InputConnectionWrapper.java:158)
  at com.android.internal.view.IInputConnectionWrapper.executeMessage (IInputConnectionWrapper.java:345)
  at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage (IInputConnectionWrapper.java:91)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1386)
```

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Fixes #1426

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Comment by mahibi** [comment]
@AndyScherzinger something went wrong here? the commit don't match the PR title...

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger something went wrong here? the commit don't match the PR title...

Pushed to the wrong branch... Fixed now 👍 @mahibi

**Review by mahibi — APPROVED** [review]

**Pull request merged**
