### PR TITLE
Use already fetched capabilities for user

### PR DESCRIPTION
**Pull request by timkrueger**
This should avoid that the capabilities not available for the server EOL
check in 'ConversationListController#onAttach'.

Missing capabilites can also have an impact on multiple actions, but the
server EOL check is the first one.

Resolves: #2418

### CODE REVIEW

**Comment by timkrueger** [comment]
@AndyScherzinger Can you have a look if that is a valid workaround in the context of the `UserManager`?

**Comment by mahibi** [comment]
for the record: this was some sort of blind coding because we were not able to reproduce the issue. However we think that this could fix the bug.
There is quite a long chain with workers and thrown events from eventbus which might caused the reported issue.

**Comment by AndyScherzinger** [comment]
I am not into the details of the user manager but the code look sensible, so I'd say let's give it a try, not sure though if it should go into 15.0.0 or rather a 15.0.1 RC shortly after the release since by now the window before the stable is very short.

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
