### PR TITLE
bump version to 13.0.0 Alpha 1

### PR DESCRIPTION
**Pull request by mahibi**
Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]
❤️ Thanks @mahibi 🙏

**Comment by AndyScherzinger** [comment]
@mahibi @timkrief see https://www.kaminsky.me/nc-dev/talk-lint/2559.html#QueryPermissionsNeeded (due to sdk30 I guess), please check with @AlvaroBrey I guess you face the issues he just fixed for files app.

**Comment by mahibi** [comment]
merged because all checks but CI were successful. CI is sleeping...

**Comment by AndyScherzinger** [comment]
👍

**Pull request merged**
