### PR TITLE
Add sorting capabilities to file browser

### LINKED ISSUE #919: Sort attachment view
Hi there,
It could be great to be able to sort the attachment view. Here is the use case:
- I have a folder containing a very long list of pictures named after the shot's date (my phone photos)
- I want to share the last picture I took
- I don't want to scroll endlessly
- I just want to change the order  (from Z to A) and pick the last picture

Have a good evening and stay safe.

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* Resolves #919
* replaces refresh action-menu with a pull-to-refresh action

### CODE REVIEW

**Comment by mahibi** [comment]
while testing the app crashed multiple times with the following error:

```
..........<d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/files/marcel/Talk/IMG_1629545162623.jpg</d:href><d:propstat><d:prop><d:getcontenttype>image/jpeg</d:getcontenttype><d:getcontentlength>2687785</d:getcontentlength><d:getlastmodified>Sat, 21 Aug 2021 11:26:08 GMT</d:getlastmodified><d:getetag>&quot;240087bc214428ca30164e9ea1cd5061&quot;</d:getetag><d:resourcetype/><oc:permissions>SRGDNVW</oc:permissions><oc:id>00059641ocqbj5czxb7u</oc:id><oc:size>2687785</oc:size><oc:favorite>0</oc:favorite><oc:owner-id>andy</oc:owner-id><oc:owner-display-name>Andy Scherzinger</oc:owner-display-name><oc:comments-unread>0</oc:comments-unread><nc:mount-type>shared</nc:mount-type><nc:has-preview>true</nc:has-preview><nc:note></nc:note></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:displayname/><d:creationdate/><nc:is-encrypted/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>
2021-09-03 09:13:35.304 29211-29431/com.nextcloud.talk2 I/okhttp.OkHttpClient: <-- END HTTP (41901-byte body)
2021-09-03 09:13:35.526 2336-3454/? D/PerfShielderService: com.nextcloud.talk2|com.nextcloud.talk2/com.nextcloud.talk.activities.MainActivity|5395|1399877441766166|511|2|120
2021-09-03 09:13:35.527 3425-3462/? W/MiuiPerfServiceClient: interceptAndQueuing:29211|com.nextcloud.talk2|5395|511|unknown|null|com.nextcloud.talk2/com.nextcloud.talk.activities.MainActivity|1399877441766166|Slow handle animation|120
2021-09-03 09:13:40.630 29211-29431/com.nextcloud.talk2 W/System.err: java.lang.NullPointerException: subscribeActual failed
2021-09-03 09:13:40.630 29211-29431/com.nextcloud.talk2 W/System.err:     at io.reactivex.Single.subscribe(Single.java:3671)
2021-09-03 09:13:40.631 29211-29431/com.nextcloud.talk2 W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2021-09-03 09:13:40.632 29211-29431/com.nextcloud.talk2 W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
2021-09-03 09:13:40.632 29211-29431/com.nextcloud.talk2 W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2021-09-03 09:13:40.633 29211-29431/com.nextcloud.talk2 W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2021-09-03 09:13:40.633 29211-29431/com.nextcloud.talk2 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-09-03 09:13:40.634 29211-29431/com.nextcloud.talk2 W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2021-09-03 09:13:40.635 29211-29431/com.nextcloud.talk2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-09-03 09:13:40.635 29211-29431/com.nextcloud.talk2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-09-03 09:13:40.636 29211-29431/com.nextcloud.talk2 W/System.err:     at java.lang.Thread.run(Thread.java:764)
2021-09-03 09:13:40.641 29211-29431/com.nextcloud.talk2 W/System.err: Caused by: java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{c2e6f4e VFED..... .......D 0,0-1080,1671 #7f0a02e7 app:id/recycler_view}, adapter:eu.davidea.flexibleadapter.FlexibleAdapter@a03586f, layout:eu.davidea.flexibleadapter.common.SmoothScrollLinearLayoutManager@d38a97c, context:com.nextcloud.talk.activities.MainActivity@b8179cc
2021-09-03 09:13:40.642 29211-29431/com.nextcloud.talk2 W/System.err:     at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3185)
2021-09-03 09:13:40.643 29211-29431/com.nextcloud.talk2 W/System.err:     at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:5720)
2021-09-03 09:13:40.644 29211-29431/com.nextcloud.talk2 W/System.err:     at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:12684)
2021-09-03 09:13:40.644 29211-29431/com.nextcloud.talk2 W/System.err:     at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:7722)
2021-09-03 09:13:40.645 29211-29431/com.nextcloud.talk2 W/System.err:     at eu.davidea.flexibleadapter.FlexibleAdapter.performInsert(FlexibleAdapter.java:2962)
2021-09-03 09:13:40.646 29211-29431/com.nextcloud.talk2 W/System.err:     at eu.davidea.flexibleadapter.FlexibleAdapter.addItems(FlexibleAdapter.java:2941)
2021-09-03 09:13:40.646 29211-29431/com.nextcloud.talk2 W/System.err:     at com.nextcloud.talk.components.filebrowser.controllers.BrowserController.listingResult(BrowserController.kt:213)
2021-09-03 09:13:40.647 29211-29431/com.nextcloud.talk2 W/System.err:     at com.nextcloud.talk.components.filebrowser.operations.DavListing$1.onSuccess(DavListing.java:60)
2021-09-03 09:13:40.648 29211-29431/com.nextcloud.talk2 W/System.err:     at com.nextcloud.talk.components.filebrowser.operations.DavListing$1.onSuccess(DavListing.java:51)
2021-09-03 09:13:40.648 29211-29431/com.nextcloud.talk2 W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
2021-09-03 09:13:40.649 29211-29431/com.nextcloud.talk2 W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:56)
2021-09-03 09:13:40.650 29211-29431/com.nextcloud.talk2 W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2021-09-03 09:13:40.650 29211-29431/com.nextcloud.talk2 W/System.err: 	... 9 more
2021-09-03 09:13:40.668 2336-3454/? W/ActivityManager:   Force finishing activity com.nextcloud.talk2/com.nextcloud.talk.activities.MainActivity
```

**Comment by AndyScherzinger** [comment]
> while testing the app crashed multiple times with the following error:

Interesting, didn't change anything here, so need to check if this also crashed before the kotlin conversion then.

**Comment by mahibi** [comment]
> > while testing the app crashed multiple times with the following error:
> 
> Interesting, didn't change anything here, so need to check if this also crashed before the kotlin conversion then.

Indeed, just reproduced the same error without the PR!

**Review by mahibi — APPROVED** [review]

**Comment by mahibi** [comment]
@AndyScherzinger merge?

**Comment by AndyScherzinger** [comment]
@mahibi yeah, fine with me 👍

**Pull request merged**
