### PR TITLE
Show error when loading chats fails

### PR DESCRIPTION
**Pull request by jld3103**
Partially addresses https://github.com/nextcloud/talk-android/issues/2346, but only shows that an error happened and doesn't offer any options.
Screenshot_1664552840

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Looks good code-wise 👍

UI-wise I tend to suggest a different approach to display this by either going for a Snackbar that can timeout or show an 'empty view' with an error icon and text hinting to retry view pull-to-refresh.

For the empty screen stuff @tobiasKaminsky might be a good contact or me 🙃

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
So I'd say feel free to merge but we should discuss a different UI approach, looping in @jancborchardt and @nimishavijay 👋

**Comment by jld3103** [comment]
@mahibi and I talked about the way we want to display this and it has to be some kind of dialog or popup because messing with all the layout visibility breaks easily and this page needs to be rewritten properlay anyway. the dialog was just the least intrusive method into the logic, but we could also make it a snackbar, yes.

**Comment by AndyScherzinger** [comment]
@jld3103 as I said all good from a technical perspective, so feel free to merge. 👍

**Comment by tobiasKaminsky** [comment]
You already have emptyList in it (https://github.com/nextcloud/talk-android/blob/9bbeb9b420d4db3a24daea78f203a5bf79db0b7d/app/src/main/res/layout/controller_conversations_rv.xml#L45) and use it already when there is no conversation available:
https://github.com/nextcloud/talk-android/blob/d8d4fde39108b2e20a2eefea3a622a6a891d0b04/app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt#L560

"just" setting the values there in case of error should be enough.

**Pull request merged**
