### PR TITLE
Make sure to set swipe-to-reply after the room info has been loaded

### LINKED ISSUE #2287: Talk 14.1.0: swipe left on a message to reply does not work any more

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Resolves #2287

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Review by timkrueger — APPROVED** [review]

**Comment by migulen** [comment]
Hello, 

Swipe-to-reply don't work in v14.1.1-RC1 from github. I think it's tagged like resolved in the changelog of v14.1.1-RC1. 

imagen

imagen


I've tested that if you open a conversation, initially it doesn't work, but,after opening the conversation If you open "conversation info" (clicking at top), and return to the conversation, it starts to work correctly until you get out of the conversation. It continues working too, if not getting out of the conversation, you change between differents apps.

I've seen that issue after installing v14.1.0, but too in v14.1.1-RC1. **Could be the patch it's no applied in v14.1.1-RC1 ?**

Thanks in advance.

*You all are doing an impressive job.*

**Comment by migulen** [comment]
ReSeeing that RC1 is from 4 days ago... and this patch is merged from yesterday... well it think it will be normal. I think i will wait until final release. :-)

**Comment by AndyScherzinger** [comment]
Hi @migulen - exactly, th efix should ship next week with the next, final build for 14.1.1 👍

**Pull request merged**
