### PR TITLE
detekt improvements

### PR DESCRIPTION
**Pull request by AndyScherzinger**
### 🖼️ Score

🏚️ Before | 🏡 After
---|---
99 | 83

### 🚧 TODO

- [x] get refactorings reviewed

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Especially https://github.com/nextcloud/talk-android/pull/4544/files#diff-613b4702fd5108bfa720e7a128cd700663fd46f7e5b8c5207c04088899cfb0b4

**Review by mahibi — APPROVED** [review]

**Comment by mahibi** [comment]
ah only now saw that "to review" was removed :D

**Comment by AndyScherzinger** [comment]
@mahibi Yes, some checks failed, so I removed the review label.
Pushed a fix, so check should turn green again now and hence ready to review/merge if the changes look good to you.

**Comment by AndyScherzinger** [comment]
I didn't want to put to many changes in since shortening methods leads to quite some code being moved around... Hence I am splitting these changes into several PRs, to drive that check to zero occurences

**Review by mahibi — APPROVED** [review]

**Pull request merged**
