### PR TITLE
File upload always fails for 1MB+

### LINKED ISSUE #2519: File upload always fails for 1MB+ version 15.0.x
### Steps to reproduce

1. Update NC Talk to version 15.0.x (15.0.0 F-Droid or 15.0.1 GPlay)
2. Attempt to upload file (take photo with HQ setting, or upload from device greater than 1 MB)

### Expected behaviour

The file should upload and become part of the conversation.

### Actual behaviour

Either-
1) Notification indicates failure.
2) Notification indicates upload freezes permanently at approximately 40%.

### Device brand and model

Pixel 3XL running factory Android 11 (GPlay), Pixel 6 Pro running GrapheneOS 13 (F-Droid), Pixel 7 Pro running GrapheneOS 13 (F-Droid)

### Android version

11 or 13

### Nextcloud Talk app version

15.0.0 F-Droid or 15.0.1 GPlay

### Nextcloud server version

24.0.6

### Talk version

14.0.5

### Custom Signaling server configured

_No response_

### Custom TURN server configured

_No response_

### Custom STUN server configured

_No response_

### Android logs

_No response_

### Server log

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by starypatyk**
This might fix #2519

These changes fixed the issue for me. I was inspired by this article on SO:
https://stackoverflow.com/a/65132840

Unfortunately I am not able to test it reasonably in the next few days.

@mahibi - feel free to reject this PR if you have a better solution.

### CODE REVIEW

**Review by mahibi — APPROVED** [review]

**Comment by MrLoverLoverMMMM** [comment]
The link does not work: Object not found!

**Comment by mahibi** [comment]
> The link does not work: Object not found!

sry. lets try https://download.nextcloud.com/android/talk-alpha/android-talk-150010008.apk

**Comment by MrLoverLoverMMMM** [comment]
in this app the sharing with files works again, thanks for the hf

**Comment by starypatyk** [comment]
@mahibi - I have noticed that this PR has been added to the [**15.0.2** milestone](https://github.com/nextcloud/talk-android/milestone/63), but the changes have been only merged into `master`, **not** backported to the `stable-15.0` branch.

**Comment by mahibi** [comment]
oh you are right 🙆‍♂️ thanks for the hint @starypatyk !!

**Pull request merged**
