### PR TITLE
Login Textfield design

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Original, corresponding Android Files client PR based on the design review by @jancborchardt and others (https://github.com/nextcloud/android/pull/7971): 

* Using container-style for text fields (initially just for the login screen since it has a specific set of colors)

### Screenshots

| Filled Address  | Error Text | Checking Server |
| ------------- | ------------- | ------------- |
|  device-2021-02-15-153947 | device-2021-02-15-155501 |  device-2021-02-15-154229 |

### Sidenote
* atm the talk client simply states the same error (see screenshot) no matter the error (e.g. server doesn't even exists Vs. talk app not installed). This could be changed but is not related to this UI PR and can be added in the future by anybody, the UI is in pace
* talk client has a icon opacity logic for enabled/disabled which the files client lacks atm (so either remove or add to the files client in the future)
* like with the files client the helper-text is brand-able

Other than that
* Hi @mahibi 👋 
* cc @tobiasKaminsky for the opacity thing 😃

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
>     * talk client has a icon opacity logic for enabled/disabled which the files client lacks atm (so either remove or add to the files client in the future)

I think this is not needed. if you want, you can of course add it on Files app, but it is not that needed…

**Comment by AndyScherzinger** [comment]
@jancborchardt I vote for also putting some more spacing between logo and input field, e.g. double it.

**Comment by jancborchardt** [comment]
> @jancborchardt I vote for also putting some more spacing between logo and input field, e.g. double it.

Yep, good call! Also agree with removing the opacity/transparency logic. More feedback:
- Can we define a max-width for that whole block of content? It looks off spanning full width, e.g. here half the width of what you have in the screenshots is already plenty. This would probably be defined in dp instead of percentage so it’s the same no matter the display size.
- The "Testing connection" and "Server does not have supported …" is not shown in the same place, would be nicer if it is. :)

**Comment by AndyScherzinger** [comment]
> Can we define a max-width for that whole block of content? It looks off spanning full width, e.g. here half the width of what you have in the screenshots is already plenty. This would probably be defined in dp instead of percentage so it’s the same no matter the display size.

I'll look into it while I am pretty sure its possible. Would add that for files client too. (Reason you see it here: files client screenshots (phone), talk (tablet) 😉 

> The "Testing connection" and "Server does not have supported …" is not shown in the same place, would be nicer if it is. :)

I'll look into it, sure 👍

**Comment by AndyScherzinger** [comment]
@jancborchardt All DONE, updated screenshots https://github.com/nextcloud/talk-android/pull/1010#issue-573476412

**Review by jancborchardt — APPROVED** [review]
Bellissimo! ✨

**Comment by AndyScherzinger** [comment]
Mille Gracie 🙏

**Comment by tobiasKaminsky** [comment]
For drone to work again, please rebase after #1012 is merged.

**Comment by tobiasKaminsky** [comment]
Rebased

**Review by mahibi — APPROVED** [review]
this looks great, thank you @AndyScherzinger !!

**Comment by mahibi** [comment]
waiting for https://github.com/nextcloud/talk-android/pull/1018 (https://github.com/nextcloud/talk-android/pull/1014 was for master, this one is for master-broken)

**Comment by mahibi** [comment]
so... we just don't know why drone doesn't use the correct email address (https://github.com/nextcloud/talk-android/pull/1021#issuecomment-784840236)

so PR is finally merged with admin rights.. thanks again @AndyScherzinger

**Comment by AndyScherzinger** [comment]
My pleasure 👍

**Pull request merged**
