### PR TITLE
Conversation avatars

### LINKED ISSUE #2555: 🖼️ Conversation avatars
See meta ticket at https://github.com/nextcloud/spreed/issues/927

- [x] Allow moderators to set an avatar for a conversation
- [x] Allow moderators to delete an avatar from a conversation
- [x] Use new avatar route as conversation icon in all code paths

### PR DESCRIPTION
**Pull request by mahibi**
resolve #2555, #1024

### 🖼️ Screenshot + Video

grafik

https://user-images.githubusercontent.com/2932790/235450887-8cecfa4b-6113-45a2-a2a2-e1480723041c.mp4

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by mahibi** [comment]
i just wanted to keep this branch up to date so i rebased on master..
but now i keep getting errors in Android Studio:

for me there are problems with the json models for UserProfile*.
AS complains "Syntax highlighting has been temporarily turned off ... because of an internal error" for some files, and these files can't be imported into other ones.

grafik

**Comment by AndyScherzinger** [comment]
@mahibi just rebased and imported into AS and had no errors, build and launched just fine on an emulator

**Comment by mahibi** [comment]
> @mahibi just rebased and imported into AS and had no errors, build and launched just fine on an emulator

i still have the error in AS (all versions up to date) but this time i could at least build and launch..

**Comment by AndyScherzinger** [comment]
I run a fresh checkout per branch, so can't tell if that has an impact or if there is some difference platform wise win/linux...

**Comment by AndyScherzinger** [comment]
@mahibi breaks avatars on v26 (and below I suspect), see production:
Screenshot_20230428_171928

**Review by AndyScherzinger — APPROVED** [review]
Fine except for the backwards compatible behavior on v26 and below, see screenshot posted earlier.

**Comment by mahibi** [comment]
Converted to draft to work on:
- backwards compatible behavior on v26
- avatarVersion (should avoid some flickering)

**Comment by mahibi** [comment]
> Fine except for the backwards compatible behavior on v26 and below, see screenshot posted earlier.

@AndyScherzinger works fine for me on NC 25. 
Or do you mean android api version??

Otherwise i changed some things again, so please test/review again if you like to.

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger works fine for me on NC 25.

@mahibi I meant Nc26, but works fine now 👍 Code looks good - feel free to merge 🚀

**Pull request merged**
