### PR TITLE
Respect participant permissions

### PR DESCRIPTION
**Pull request by timkrueger**
This PR adds support for the following permissions:

- [x] 2 Start call
- [x] 4 Join call
- [x] 8 Can ignore lobby
- [x] 16 Can publish audio stream
- [x] 32 Can publish video stream
- [ ] ~64 Can publish screen sharing stream~ _Screen sharing is not supported in NC Talk for Android._
- [x] 128 Can post chat message, share items and do reactions

__Limitation: The permissions don't get updated during a call. Only a reload of the conversation will get permission updates!__

### CODE REVIEW

**Comment by timkrueger** [comment]
The implementation of the publish permissions will wait for changes of @danxuliu to avoid massive conflicts in the `CallActivity`.

**Comment by nickvergessen** [comment]
Can this be merged in the meantime and a follow up be used for the remaining permissions?

**Comment by timkrueger** [comment]
> Can this be merged in the meantime and a follow up be used for the remaining permissions?

The blocking changes already in the master. So I implement the missing three today.

**Comment by timkrueger** [comment]
> Limitation: The permissions don't get updated during a call. Only a reload of the conversation will get permission updates!

Can we live with that limitation @nickvergessen ? I'm also not happy with that. But before make the permissions update-able on the fly I want to make a bigger refactoring of the 'CallActivity'. I plan that to do for 15.1!

**Comment by nickvergessen** [comment]
> Can we live with that limitation @nickvergessen ? I'm also not happy with that. But before make the permissions update-able on the fly I want to make a bigger refactoring of the 'CallActivity'. I plan that to do for 15.1!

Respecting any permission is a step forward, so yeah let's do it.

**Review by mahibi — APPROVED** [review]

**Pull request merged**
