### PR TITLE
Change icon

### PR DESCRIPTION
**Pull request by mario**
cc @stefan-niedermann @jancborchardt for the icon background change.

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Hmm. Will this new background also be adopted on the Files app? @tobiasKaminsky 

grafik

**Comment by mario** [comment]
@stefan-niedermann yes.

**Comment by stefan-niedermann** [comment]
Thanks for the information :) I will adjust Notes & Deck and prepare some Pull Requests for the other apps out there.

**Comment by stefan-niedermann** [comment]
# Adjust icon backgrounds in 3rd-party android apps

Pull requests exist for:

- [x] News https://github.com/nextcloud/news-android
- [x] Notes https://github.com/stefan-niedermann/nextcloud-notes (merged)
- [x] Deck https://github.com/stefan-niedermann/nextcloud-notes (merged)
- [x] Phonetrack https://gitlab.com/eneiluj/phonetrack-android
- [x] Bookmarks https://gitlab.com/bisada/OCBookmarks
- [x] Reader https://github.com/schaal/ocreader
- [x] SMS https://github.com/nerzhul/ncsms-android
- [ ] Passwords https://github.com/daper/nextcloud-passwords-app

**Comment by jancborchardt** [comment]
Wow @stefan-niedermann! :O Thanks a ton, that's so cool!!

Soon I'll also hopefully finish a new Notes app icon that you asked for so long. :)

**Comment by stefan-niedermann** [comment]
@mario F-Droid still displays the old icon. Maybe you can have a look into this?

**Comment by mario** [comment]
Because there's no new release yet.

**Comment by stefan-niedermann** [comment]
Oh :) nevermind then

**Comment by stefan-niedermann** [comment]
Over 3 months and a release (`8.0.8`) later - when can we expect the new app icon for Talk? 🙂

It just looks odd at the App stores :-/

**Comment by mario** [comment]
The icon is definitely not a priority. My workload is one of 3-4 developers atm - the icon will be there with 9.0.0 beta1, whenever that is.

**Pull request merged**
