### PR TITLE
Implement text formatting via markdown

### LINKED ISSUE #3154: Basic text formatting for chat messages
In alignment with https://github.com/nextcloud/spreed/issues/1027 implement basic text formatting for chat text based on standard markdown

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Resolves #3154 

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
Screenshot_20230710_105102|Screenshot_20230710_104336

**Note** 
Items aren't interactive, so you can't tick of checkboxes ;)

### 🚧 TODO

- [x] apply to different messages 
- [x] unify formatting code for reuse

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by SystemKeeper** [comment]
Hey @AndyScherzinger, code blocks with 3 back ticks are just rendered as a block with monospaced font, right?

**Comment by AndyScherzinger** [comment]
> Hey @AndyScherzinger, code blocks with 3 back ticks are just rendered as a block with monospaced font, right?

Yes.currently I don't plan to add support for syntax highlighting that seems to be just over the top from my point of view 👍

**Comment by mahibi** [comment]
great :+1: :+1: 

one random test where the time is not correctly aligned:

grafik

**Comment by mahibi** [comment]
not sure how much work it might be to improve tables? ...

grafik

**Comment by AndyScherzinger** [comment]
> one random test where the time is not correctly aligned:
> not sure how much work it might be to improve tables? ...

@mahibi, I removed table rendering and the time alignment issue is also present on master (this is due to the parent layout component (flex box) :(  So I would ignore that one.

Screenshot_20230710_175127

**Review by mahibi — APPROVED** [review]

**Pull request merged**
