### PR TITLE
Message search

### PR DESCRIPTION
**Pull request by AlvaroBrey**
- [x] Global message search
  - [x] Load messages from unified search
  - [x] Show message matches
  - [x] "Load more" for requesting more pages (currently only first 5 shown)
  - [x] Open relevant conversation when result is clicked
      - [x]  Scroll to message if possible
- [x] Search in conversation
     - [x] Everything except scroll to message
     - [x] Scroll to message if possible
- [x] Enable only if capability is present, ref https://github.com/nextcloud/spreed/pull/7439

Signed-off-by: Álvaro Brey <alvaro.brey@nextcloud.com>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Hi @AlvaroBrey just as a side-note in case you are up for it since it kills the diff for the controller and creates a multi-purpose PR you could migrate to kotlin since this will be the last java based controller with butterknife in use after #2043 will be merged.  If not we'll do it afterwards :)

**Comment by AlvaroBrey** [comment]
> Hi @AlvaroBrey just as a side-note in case you are up for it since it kills the diff for the controller and creates a multi-purpose PR you could migrate to kotlin since this will be the last java based controller with butterknife in use after #2043 will be merged. If not we'll do it afterwards :)

If that's OK, I'd prefer to do it in a separate PR. Otherwise this will be a mess to review, the diff is going to be large enough as it is. Maybe I can even do the migration first, and then rebase this PR.

**Comment by AlvaroBrey** [comment]
@AndyScherzinger I tried to do the kotlin/binding conversion but I ran into some troubles, mostly due to not feeling confident enough in the app architecture to modify stuff. If you want you can do the conversion on master and then I will rebase this.

**Comment by AndyScherzinger** [comment]
@AlvaroBrey let'S do it the other way around - feature first :) -  we can migrate the controller after this feature is in, no worries and yes, this one will be a mess again for the migration to review, but that is perfectly fine. We are getting there :)

**Comment by AlvaroBrey** [comment]
This is mostly ready functionality-wise; still need to figure out when to enable/disable message search depending on capabilities.

For ease of review:
- In the conversation list, the message results get prepended to the existing adapter. This requires  some workarounds due to the way the adapter library works, but I couldn't make it work otherwise.
- The search in a conversation has been implemented as a new activity.
- There's a `MessageSearchHelper` class that is used from both the new activity's viewmodel, and the `ConversationListController`.

**Comment by AlvaroBrey** [comment]
@mahibi @timkrueger can you have a look and see if there's any glaring errors in my code, and also test the functionality? I still have to figure out when/how to enable and disable it, but the main stuff should be ready

**Review by timkrueger — APPROVED** [review]
For me it is working as expected. Good work 💙

With the knowledge of our previous pair programming sessions your implementation is very understandable for me. Thank you :smiley: 

Otherwise I have nothing to complain about 😉

**Comment by mahibi** [comment]
Well done @AlvaroBrey :1st_place_medal: :1st_place_medal: :1st_place_medal:

**Pull request merged**
