### PR TITLE
Introduce SearchBar/Toolbar in dark/light design

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

Follow-up for #1077 adding further UI enhancements:

* dark/light toolbar
* new searchbar
* tinting status bar and navigationbar accordingly

|:sunny:light (old)|:sun_with_face:light (new)|:sun_with_face:light (new search)|
|---|---|---|
|light|light_new|light_new_search|

|:new_moon:dark (old)|:new_moon_with_face:dark (new)|:new_moon_with_face:dark (new search)|
|---|---|---|
|dark|dark_new|dark_new_search|

### CODE REVIEW

**Comment by jancborchardt** [comment]
Wow wow wow! :D Reeeally nice!

Only detail feedback, both for when the search is active:
- [ ] It would look a bit nicer if the back button is horizontally aligned with the avatars below, so moved a bit to the right
- [ ] Similar for the search text, it could be moved a bit to the right so it’s flush left with the text of the conversations below

Otherwise :rocket: !

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Blocking to make sure a feature we just build still works

**Comment by AndyScherzinger** [comment]
@nickvergessen sounds good, I still have to incorporate the feedback 👍 so no worries. I can rebase this one afterwards and take care of issue in case there are any 💪

**Comment by mahibi** [comment]
font color for system standard needs to be changed

dark
grafik

white
grafik

system standard
grafik

**Comment by mahibi** [comment]
when logging in with a new account it looks like this currently:
grafik

**Comment by AndyScherzinger** [comment]
Some Feedback:

* @mahibi fixed all issues reported by you 👍 
* @jancborchardt this is rather tricky since I can't:
  *  change the back arrow positioning, which is why it left-aligns with the avatars
  * similar for search text -  I can't really influence it's positioning either :/ so this also depends on the content layout, see screenshots for conversations list and contacts list... 

|search_conversation_list|contacts_search|

**Comment by AndyScherzinger** [comment]
❗ rebased ❗

**Review by jancborchardt — APPROVED** [review]
Good design-wise! (From screenshots, didn’t test) :+1:

**Review by mahibi — APPROVED** [review]

**Comment by mahibi** [comment]
thank you Andy!! 👍👍👍👍👍👍👍👍👍

**Pull request merged**
