### PR TITLE
Reply from notification

### LINKED ISSUE #230: Quick reply via notification
Hi !

I'd be really happy if, from the notification itself, I'm could 
* reply to the last message
* mark the message as read
(i.e. without leaving the notification zone)

The usual suspect, Signal & Whatsapp, do this and this is a feature I use *_a lot_* !

Suprisingly, I could not find an existing issue for this !
Thanks
GLLM

### PR DESCRIPTION
**Pull request by starypatyk**
I wanted to make an experiment - how difficult it is to add a **Reply** action to the notifications. Turned out to be simpler than expected. 😉

This should partially resolve #230 and #1428. This is also a pre-requisite for #1208.

This seems to work already, however I would like to make some additional changes:

- [x] ~~Notify the user when reply could not be sent~~
- [x] Refactor code in NotificationWorker.java:
  - [x] [Extract common code to load user avatars for notifications](https://github.com/nextcloud/talk-android/pull/1923/commits/59ccfd8044e42e365b749de9ba592dca8ed75c5a)
  - [x] [Extract code handling chat (message) notifications to shorten the showNotification function](https://github.com/nextcloud/talk-android/pull/1923/commits/b2510041790e17d18d0452c6fb215287bdaff6c7)
- [x] Additional refactoring [here](https://github.com/nextcloud/talk-android/pull/1923/commits/296cb0721fc9fb97adcea415f631f31a1773596c), [here](https://github.com/nextcloud/talk-android/pull/1923/commits/2857e40634fa61cc5875813dfbb50d4c40a9be63) and [here](https://github.com/nextcloud/talk-android/pull/1923/commits/7a0d58120aa874db7e81ef94a20767094cbc706b).
- [x] [Remove suspicious setAction call](https://github.com/nextcloud/talk-android/pull/1923/commits/c9a3f75384f6cbc1aceea24aaceb130d8d2ea79e)

### CODE REVIEW

**Comment by starypatyk** [comment]
@mahibi  @AndyScherzinger - I have done _some_ refactoring of the **NotificationWorker** class. I think that the code path responsible for preparing chat notifications is more readable now. However, I have not performed refactoring of the other parts of the class. It is a tough question when to stop refactoring... :wink:

There is also a question of error handling - i.e. how the application should behave when the reply message cannot be sent. I wanted to use code in **ChatController** as a guide, but [apparently this case is not handled very well in ChatController](https://github.com/nextcloud/talk-android/blob/4d00d1e0e69d9d72537a2d1385234b8b06ed4ff4/app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt#L1920).

I understand that my PR blocks progress on #1945.

What would you suggest? Merge as is? Try to implement some basic error handling? Keep refactoring?

PS. I do not fully understand what happened in Git. I see that the **drone** bot auto-merged from master into this branch :+1:. But why does GitHub display 59 files as changed? :disappointed: The diff between this branch and master looks as expected in Android Studio.

**Comment by AndyScherzinger** [comment]
@starypatyk @mahibi I guess the best for now would be to just trigger a `Toast` that replying failed. 

As for the added commits you see on Github, just rebase against latest master and the commits will disappear 👍

**Comment by mahibi** [comment]
just tested this and works fine :+1: 

i suggest to:
- for now stop refactoring and try to get this in soon. Really appreciate the refactoring as it's quite necessary! However, we need to start implementing #1991 and #1992 soon which might also lead to some refactoring regarding the same code parts
- for now make a toast if replying failed
- rebase on master so the diff should be fixed

**Comment by AndyScherzinger** [comment]
Also @starypatyk if you don't want or can rebase the branch I can do that for you after the Toast is in because if somebody else rebases it you need to do a fresh checkout :/ If you want somebody else to implement the Toast, just let us know and we can cover that, you already did a great job implementing the replies and doing the refactoring 👍

**Comment by starypatyk** [comment]
@AndyScherzinger - I have implemented showing a toast on error. However there are two problems with this approach:

- The toast is barely visible and most likely will not be noticed by users.
- It is still necessary to "re-show" the notification (with the same ID) in order to get rid of the spinner shown by the system when sending the reply.

I think a different approach will be more appropriate - showing an "error notification" - something like this:
obraz

I have a preliminary implementation, hope to have something commitable tomorrow.

**Comment by starypatyk** [comment]
@AndyScherzinger @mahibi - feel free to rebase/merge this PR if this will help you with other tasks. I should be able to handle whatever Git juggling is required on my side.

**Comment by AndyScherzinger** [comment]
@starypatyk did you push the toast to the branch?

**Comment by starypatyk** [comment]
> @starypatyk did you push the toast to the branch?

No I have not. In my opinion it does not make sense to do it. Getting the error notification is not that complex and I can easily add it in another PR. If you want to rebase/merge - please go ahead with the current state of the branch.

**Comment by AndyScherzinger** [comment]
❗ rebased ❗ 

Merge after CI DONE ✅

**Comment by mahibi** [comment]
thank you very much @starypatyk , well done!! :1st_place_medal:

**Comment by AndyScherzinger** [comment]
Yes, thanks a lot @starypatyk 🏅

**Pull request merged**
