### PR TITLE
Improves visiblity of text and URLs in chat view.

### LINKED ISSUE #834: beta5: Text color for own messages has too little contrast in the light theme
The background of the sent message is too dark.

obraz

obraz

App:
Android 10
Nextcloud Talk 9.0.0beta5

### PR DESCRIPTION
**Pull request by dan0xii**
Closes #834.

| Before | After | 
| --------- | ------ |
| screenshot-2020-09-25_18 13 54 403  screenshot-2020-09-25_18 14 13 259 |  screenshot-2020-09-24_19 33 14 533 screenshot-2020-09-24_19 32 13 585  |

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks @dan0xii :+1: 

Mind to add a before image? It's easier to review then.

**Comment by jancborchardt** [comment]
Good stuff! Only thing: In dark mode, links in messages from others are not so readable, a lighter blue would be better. :)

**Comment by dasbiswajit** [comment]
> Good stuff! Only thing: In dark mode, links in messages from others are not so readable, a lighter blue would be better. :)

Maybe white is also better. Which is more visible in dark mode.

**Review by dasbiswajit — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
Rebased, so CI should run fine now

**Pull request merged**
