### PR TITLE
Vertically center cenversation item icons

### PR DESCRIPTION
**Pull request by AndyScherzinger**
follow up for #331 
conv1_centered

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Code changes looks good to me.

Do we want to use the same labelling system here? Then with "2. to review" this PR would show up in our tracking PR site, I created.

**Comment by AndyScherzinger** [comment]
@jancborchardt @mario this is the PR re-adding the vertically centered alignment of the icons. Depending on your feedback the PR can be merged or closed.

@tobiasKaminsky process as illustrated by you would be fine with me while I'd say pull-approve should be one review not two.

**Comment by mario** [comment]
@AndyScherzinger I've merged your PR already and it's fine by me for starters so I'd like to close this one.

@tobiasKaminsky codacy already should work really.

Like I said earlier, I'm fine with using PRs on the condition that it's reviewed technically, and not the general direction since I know the most about this app at the moment and its users. In fact, I believe reviews would help the overall quality of the app.

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky codacy already should work really.

Strange, that it did not showed up here.

> Like I said earlier, I'm fine with using PRs on the condition that it's reviewed technically, and not the general direction since I know the most about this app at the moment and its users. In fact, I believe reviews would help the overall quality of the app.

Fine for me. Looking forward to the first PRs :+1:

**Pull request closed without merging**
