### PR TITLE
add openGraph link previews

### LINKED ISSUE #2419: Implement link previews
like in the server app:
https://github.com/nextcloud/spreed/pull/7822

### PR DESCRIPTION
**Pull request by mahibi**
resolve  #2419

grafik

## Testing
for testing with NC setup on localhost this snippet might be helpful to paste in LinkPreview.kt to modify the referenceThumbUrl.
Because modifying `overwrite.cli.url` in `config.php` somehow fails sometimes for me...

```
  // just for developing because overwrite.cli.url fails sometimes....
  referenceThumbUrl = referenceThumbUrl?.replace(
      "http://nextcloud.localhost:8210",
      "http://10.0.2.2:8210"
  )
```

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@mahibi couldn't check it out yet, what happens in case of replying (inlining) such messages?

**Comment by mahibi** [comment]
> @mahibi couldn't check it out yet, what happens in case of replying (inlining) such messages?

good point. it looks like this:

grafik

other messengers have a tiny thumbnail in this case. 
But for now skipping the preview is totally fine in my opinion.

**Comment by mahibi** [comment]
> If you make a long press on a link preview part of a message bubble, no menu (reply, forward, ...) is shown. 

fixed

**Pull request merged**
