### PR TITLE
Switch webRTC dependency to gradle dependency managed 

### LINKED ISSUE #2972: F-Droid - webrtc should be either built from source or pulled from maven
ref: https://f-droid.org/docs/Inclusion_Policy/

Since: https://github.com/nextcloud/talk-android/tree/v14.0.0 ref: https://github.com/nextcloud/talk-android/commit/bad5b5f9bccae7f88eb533cf900094956487849f#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R260

ref: https://github.com/nextcloud/talk-android/blob/v16.0.1/buildSrc/src/main/groovy/com/nextcloud/talk/gradle/DownloadWebRtcTask.groovy#L48

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4159622028#L957

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/d06a8ede972819102f2ec2d5e329f2f7d150aba3

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Resolves #2972 

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by mahibi** [comment]
DownloadWebRtcTask.groovy should be deleted

**Comment by mahibi** [comment]
- [ ] when this is merged, docu at https://github.com/nextcloud-releases/talk-clients-webrtc#build-for-android should be updated

**Comment by AndyScherzinger** [comment]
> DownloadWebRtcTask.groovy should be deleted

DONE! Nice catch @mahibi 👍 https://github.com/nextcloud/talk-android/pull/2977/commits/1243fe4c03a2c962a2754e5937619975837c35ff

**Comment by AndyScherzinger** [comment]
We could consider backporting to see if a 16.0.2 would build and go through on f-droid if we want to not run into the situation with 17.0.0 - what do you think?

**Comment by mahibi** [comment]
@AndyScherzinger also see https://github.com/nextcloud-releases/talk-clients-webrtc/pull/7

**Review by mahibi — APPROVED** [review]

**Pull request merged**
