### PR TITLE
Show "contact-name" and "contact-photo" when applicable

### LINKED ISSUE #1135: Make sharing vcard files display better
## Steps to reproduce
1. Create a contact in your contacts
2. Share the vcard (.vcf) to a talk conversation
3. Clicking the file should allow adding the contact to your phones address book app

### Expected behaviour
It looks appealing and clear that it is a contact, maybe some meta data is displayed (FN, photo?) Check https://github.com/nextcloud/spreed/issues/5498 for potential APIs

### Actual behaviour
Screenshot_2021-04-19-11-13-22-765_com nextcloud talk2

### PR DESCRIPTION
**Pull request by nickvergessen**
Before | After
---|---
Bildschirmfoto von 2021-06-17 14-25-28|after

But now it looks a bit like an image file. Maybe @AndyScherzinger can restyle it to look a bit more like:
https://github.com/nextcloud/spreed/pull/5731#issuecomment-863159882

Fix #1135

### CODE REVIEW

**Comment by mahibi** [comment]
didn't work for me yet. 
- downloaded a vcf from nextcloud addres book and pasted it in the chat.
- created a contact in my phone with photo and shared contact to nextcloud talk app
no name of photo was shown..

from where and how did you share the vcf? @nickvergessen

**Comment by nickvergessen** [comment]
Requires https://github.com/nextcloud/spreed/pull/5731 to be merged first

**Comment by nickvergessen** [comment]
Merged now

**Comment by AndyScherzinger** [comment]
@nickvergessen I can polish the UI, sure thing 👍

Within the PR in case I am quick enough or as a followup. So. If it is working fine for you, don't wait for me 😉

**Comment by nickvergessen** [comment]
✨  UI fix up as always @AndyScherzinger  😎

**Review by mahibi — APPROVED** [review]

**Pull request merged**
