### PR TITLE
Use chip view for pill-style unread messages counter

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

This change has been made due to the design review feedback (which unfortunately is based on `master`not on `master-broken`!)

> Android: Unread marker in pill-style instead of oval

The redesigned app's code-base is using circular backgrounds already (which has it's downsides imho regarding text size etc.)

Also beware that I changed the avatar sizes to 40dp which is the default defined in material design for 2 line items, see https://material.io/components/lists#specs -> 2-line items

Please see attached the before/after screenshots dark/light

|light (before)|light (after)|
|---|---|
|light|light_new|

|dark (before)|dark (after)|
|---|---|
|dark|dark_new|

pinging @mahibi as well as @nextcloud/designers for review/feedback

dark version with layouting lines
dark_new_lines

### CODE REVIEW

**Review by mahibi — APPROVED** [review]

**Review by ma12-co — APPROVED** [review]
:ok_hand:

**Comment by AndyScherzinger** [comment]
Latest commit re-adds the "lost" spacing between conversations, sry...
device-2021-03-23-212623

**Comment by mahibi** [comment]
thanks @AndyScherzinger :)

**Comment by AndyScherzinger** [comment]
My pleasure @mahibi 😃

**Pull request merged**
