### PR TITLE
Android Studio 4.2 Update

### PR DESCRIPTION
**Pull request by AndyScherzinger**
WiP: Changes necessary in order to get code base to build/compile with Android Studio 4.2
Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
It is again an issue with the various code generators... It works on CI but not in Android Studio. The difference is Java 8 VS Java 11.

Cc @mahibi @tobiasKaminsky @nickvergessen I don't have an idea yet how this can be fixed 😒

**Comment by tobiasKaminsky** [comment]
> The difference is Java 8 VS Java 11.

It seems that with AS 4.2 Java 11 is bundled and thus should be used as default.
You can switch to it in File -> Project Structure -> SDK Location

For me it helped to use Java 11 and then 
./gradlew --no-build-cache cleanBuildCache clean assembleGplay

after that I could start/build/run it again with AS.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky for me the error remains (fresh checkout of this branch, open in AS42, run your command via the gradle tab):

```
error: Parceler: Code generation did not complete successfully.
  org.parceler.transfuse.transaction.TransactionRuntimeException: Encountered ErrorType UserEntity, unable to recover
```

**Comment by tobiasKaminsky** [comment]
> run your command via the gradle tab):

Can you run it within terminal? I am not sure if gradle tab behaves different.
Is the command running fine?

**Comment by AndyScherzinger** [comment]
> Can you run it within terminal?
I ran it in the gradle tab and outside of AS on the actual command line

**Comment by tobiasKaminsky** [comment]
Which java version do you use normally?
Which version is installed for you in AS?
Which version is used for you in the project?

**Comment by AndyScherzinger** [comment]
For documentation and possible solution: https://github.com/johncarl81/parceler/issues/394

**Comment by mahibi** [comment]
Since i updated AS to 4.2 i always get

`error: Parceler: Code generation did not complete successfully.`
and
```
Execution failed for task ':app:kaptGplayDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```
when trying to start via the debug icon. This happens with this branch and all other branches.
As a workaround i always have to execute

`./gradlew --no-build-cache cleanBuildCache clean assembleGplay` 

which takes quite a long time. So keeps really slowing me down..
Any other ideas for workarounds/solutions? 🤷‍♂️

**Comment by AndyScherzinger** [comment]
> Any other ideas for workarounds/solutions?

If you set Java to v8 instead of v11 in the IDEs settings it works just fine while I don't consider any of the known workarounds feasable since it should always be Checkout->Import->Run and be done with it. Any settings change or special command that needs to be triggered manually each time is a proper solution :/

**Comment by mahibi** [comment]
first had some trouble with AS not accepting the java8 path ("Please choose a valid JDK 11 directory") but this did it for now:

`source /etc/environment`
`echo $JAVA_HOME` copy this path to "File - Project structure - SDK location - JDK location"

**Comment by AndyScherzinger** [comment]
Obsolete

**Pull request closed without merging**
