### PR TITLE
i18n: Add a space

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by mahibi — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
checking back with @jancborchardt if this is how we do the ellipsizing in general

**Comment by Valdnet** [comment]
@AndyScherzinger To my knowledge, this is correct, which does not prevent the text strings from being unified in the same way, whether they are correct or not.
But please check with @jancborchardt.

**Comment by nickvergessen** [comment]
> checking back with @jancborchardt if this is how we do the ellipsizing in general

yes it is.
Space before `…` if it's not that word being trimmed

**Pull request merged**
