### PR TITLE
Fix NullPointerException on (first) account creation with client certificates (#195)

### PR DESCRIPTION
**Pull request by stephanritscher**
I was able to reproduce and fix (at least for me) the problem described in #195 

Signed-off-by: Stephan Ritscher <no3pam@gmail.com>

### CODE REVIEW

**Comment by mario** [comment]
Thanks!

**Comment by jancborchardt** [comment]
Hi @stephanritscher we have a "Talk development chat" where Talk app contributors hang out. We can add you with a guest account via your email address, if you like? :)

**Comment by stephanritscher** [comment]
Hi @jancborchardt,
thanks for your offer. I currently don't use Nextcloud Talk since my Nextcloud instance is hosted on a SBC which is probably not strong enough for hosting Nextcloud talk for productive use. While I'm still interested in contributing, I rather focus on software I actively use - maybe another time later.
Best regards,
Stephan

**Comment by jancborchardt** [comment]
@stephanritscher sure – thanks for your reply, and just let us know if you are interested in contributing again and joining the chat. :)

**Pull request merged**
