### PR TITLE
Push token recovery should not use the standard httpClient object 

### LINKED ISSUE #2218: switching accounts fails / wrong username shown in account switcher
## Steps to reproduce
there exist 2 users: userA and userB

1. login with userA
2. go to account switcher
3. BUG: avatars are shown correctly, but userA has the name of userB
4. keep userA selected. go to some conversation and send a message
5. BUG: message is sent as userB
6. go back to account switcher and select userB
7. go to the conversation and send a message
8. BUG: message is sent as userA

this doesn't always happen but sometimes.

### Expected behaviour
- names in account switcher match the avatars
- actions are not executed as another user

i guess this is caused by the room migration..

## Device information
**Talk version:** master (>= 14.2.0 Alpha 02)

## Server information
sermo

### PR DESCRIPTION
**Pull request by AndyScherzinger**
...and its cookieStore

Resolves #2218

Issue had been introduced by #1776 

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Comment by mahibi** [comment]
i tested a lot and can't reproduce the bugs :+1:
Well done @AndyScherzinger  :1st_place_medal: :+1:

**Review by mahibi — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Thanks @mahibi - tested the weeklies between 13.0.0 and 14.0.0 💪 until I hit the faulty behavior, then the PRs between, luckily it was the first PR after a weekly 🎉

**Pull request merged**
