### PR TITLE
remove ExtraTranslation flags

### PR DESCRIPTION
**Pull request by AndyScherzinger**
... since linter config should already cover this

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I would revert this one, as on line 23 there is the proper prefix included.

**Comment by MorrisJobke** [comment]
And transifex already liked it before your merge: https://github.com/nextcloud/talk-android/commit/87b142009f98d47abc5c4370fe817b134455d8e2

**Comment by AndyScherzinger** [comment]
> I would revert this one, as on line 23 there is the proper prefix included.

Thanks, I'd nevertheless keep it since the two lines I fixed where duplicate issues with the linter config. Other than that the tools namespace is used in other areas of the file, so still needed, all good I guess. :)

**Pull request merged**
