### PR TITLE
Fix #884

### LINKED ISSUE #884: Crash - AnroidLogger() with Level.INFO, Koin Logger, Kotlin update
https://github.com/InsertKoinIO/koin/issues/847

### PR DESCRIPTION
**Pull request by armantorkzaban**
just a minor change to make the app run

### CODE REVIEW

**Comment by violoncelloCH** [comment]
whoops, did you intend to close it @armantorkzaban ?

**Comment by armantorkzaban** [comment]
Not really. I will reopen it.
 I don’t know what happened 🤷‍♀️

**Comment by violoncelloCH** [comment]
hmm, maybe you accidentally deleted the branch in your fork repository ? (I think in that case a PR is closed automatically)
you should be able to recreate the branch and then reopen this Pull Request...

**Comment by armantorkzaban** [comment]
Yes, seems to be the reason!

**Pull request closed without merging**
