### PR TITLE
decreased the Icon size in notification bar 

### LINKED ISSUE #2945: Icon in notification bar is too large
### Steps to reproduce

1. Receive message from someone

### Expected behaviour

The notification icon should be the same size as the icons of other messenger apps like whatsapp or signal.

### Actual behaviour

The icon is larger than other icons.

### Device brand and model

Nokia X10

### Android version

11

### Nextcloud Talk app version

16.0.0

### Nextcloud server version

25

### Talk version

16.0.0

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Android logs

_No response_

### Server log

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Smarshal21**
fix #2945

Decreased the icon size by 13 percent. 
### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by mahibi** [comment]
> @mahibi could you please confirm if the icon size is still larger and let me know the changes as i cant test the notification as a developer

this doesn't change the size for the notification icon but for the login screen, which is not what we want.
i'm not sure if there is an easy way to change it for notifications.
@AndyScherzinger iirc we had this topic earlier, can you remember?

**Comment by Smarshal21** [comment]
> > @mahibi could you please confirm if the icon size is still larger and let me know the changes as i cant test the notification as a developer
> 
> this doesn't change the size for the notification icon but for the login screen, which is not what we want. i'm not sure if there is an easy way to change it for notifications. @AndyScherzinger iirc we had this topic earlier, can you remember?

oh my bad

**Comment by Smarshal21** [comment]
> > @mahibi could you please confirm if the icon size is still larger and let me know the changes as i cant test the notification as a developer
> 
> this doesn't change the size for the notification icon but for the login screen, which is not what we want. i'm not sure if there is an easy way to change it for notifications. @AndyScherzinger iirc we had this topic earlier, can you remember?

ig that changes both the logo on desktop and on the notification bar 
Screenshot 2023-08-25 at 3 56 03 PM
ptal at the above code
am i right?

**Comment by AndyScherzinger** [comment]
Afaik the easiest way would be to add some 'padding' to the logo vector itself.

That would slightly resize the login image and the notification icon and is probably fine.
Else we would need 2 distinct vector graphics which just makes life harder for brandings.

**Comment by Smarshal21** [comment]
> Afaik the easiest way would be to add some 'padding' to the logo vector itself.
> 
> That would slightly resize the login image and the notification icon and is probably fine. Else we would need 2 distinct vector graphics which just makes life harder for brandings.

Done @AndyScherzinger 
ptal

**Review by mahibi — APPROVED** [review]

**Comment by mahibi** [comment]
great @Smarshal21 :+1:

**Pull request merged**
