### PR TITLE
Migrate ContactsController to kotlin + viewbinding

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@mahibi see also https://github.com/nextcloud/talk-android/pull/2022#issuecomment-1124215414 for some hints

**Comment by mahibi** [comment]
when opening the search in contacts view the loading spinner immediately appears & won't hide

grafik

**Comment by mahibi** [comment]
tested a lot and can't make it crash :+1:

**Comment by AndyScherzinger** [comment]
@mahibi issue fixed via https://github.com/nextcloud/talk-android/pull/2022/commits/a88992f294515caaec80180940c2883dfcb72edb - I made a mistake during the migration, see the original https://github.com/nextcloud/talk-android/pull/2022/commits/38dd33590e659dbc67a8927fcc714f8c5b10e70a#diff-4dafa87f672a772fefa6e67e9ad0a5980ac854f8c712bf23ec95522ef2396defL770 

So all good to go now, did another rebase

**Review by mahibi — APPROVED** [review]

**Pull request merged**
