### PR TITLE
[WIP] Migrating from the MaterialPreferences library to native

### PR DESCRIPTION
**Pull request by rapterjet2004**
[MaterialPreferences ](https://github.com/yarolegovich/MaterialPreferences)is unmaintained and the UI looks dated. This PR is to migrate to a native solution, and adhere to the modern material 3 design. _https://github.com/nextcloud/talk-android/issues/3050#issuecomment-1569538231_ This way the app becomes more maintainable in the long run and reduces the use of 3rd party dependencies. 

Signed-off-by: Julius Linus julius.linus@nextcloud.com

# 🖼️ Themed Screenshots
image

## Conversation Info Activity

🏡 After
image

image

## Settings Activity
 🏡 After
image
image

# 🚧 TODO
## UI
- [x] Migrate Notification Settings Item XML
- [x] Migrate Guest Access Settings Item XML
- [x] Migrate Webinar Info Item XML
- [x] Migrate Conversation Info XML
- [x] Migrate Settings Activity XML      
## Back end
- [x] Migrate Conversation Info Activity 
- [x] Migrate Guest Access Helper           
- [x] Migrate Settings Activity                                              
- [x] Migrate from UserInputModule in Settings Activity
- [x] Migrate from StorageModule / Conversation Info Activity
- [x] Remove it from the build gradle
- [ ] Get it reviewed

# 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by mahibi** [comment]
Didn't yet find the time to look at the code but quickly gave it a try on my device. just some findings:

1 vertical alignment of text
2 horizontal alignment of text
3 margin between elements
4 vertical alignment of icons

screesnhot1|screeshot2
------- | -------- 
grafik | grafik



i guess @AndyScherzinger has opinions on the design, maybe also on the chosen elements / sizes ..?

**Comment by rapterjet2004** [comment]
Alright I implemented the UI changes along with some others, how does this look
image
image
image

**Comment by AndyScherzinger** [comment]
For reference, my design changes are based on https://m3.material.io/components/lists

**Comment by AndyScherzinger** [comment]
@rapterjet2004 can you rebase to latest master, else I would have to re-install and loose all accounts? Thanks in advance 💙

**Comment by AndyXheli** [comment]
I noticed that the proxy type box was empty on this app but the default is no proxy

**Comment by rapterjet2004** [comment]
> I noticed that the proxy type box was empty on this version but the default is no proxy

@AndyXheli  That's odd, It seems to be functioning correctly on my emulator. Although I don't have a physical device yet, so I'm not sure if the behavior is any different. Here's a video.

https://github.com/nextcloud/talk-android/assets/69230048/a8ffd25e-b25e-466b-aeec-7fa936805cba

**Comment by AndyXheli** [comment]
Hmmmm I just reinstalled it and went back into settings and nothing is selected please see screenshot how it looks 

Oh perfect!! Thank you so much.

**Comment by AndyXheli** [comment]
Perfect! Thank you so much.

**Comment by mahibi** [comment]
it looks like we have some fun work ahead of us here with merge conflicts. we can do this together if you want @rapterjet2004

**Pull request merged**
