### PR TITLE
✍️ Typing indicators

### LINKED ISSUE #2930: Support "Typing indicators"
- Overview issue at https://github.com/nextcloud/spreed/issues/9248

---

- [ ] When the chat input is non empty a signaling message is sent in periodical interval
- [ ] When the signaling messages is received a small max contrast line is shown above the chat input

### PR DESCRIPTION
**Pull request by mahibi**
resolve #2930 

### 🖼️ Screenshots

not typing | typing | settings
------- | -------- | -------- 
grafik | grafik | grafik

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]
LGTM

**Comment by AndyScherzinger** [comment]
Fine codewise besides the code checks detections

**Comment by nickvergessen** [comment]
🎉  gj!

**Pull request merged**
