### PR TITLE
i18n: Change style of sentence

### PR DESCRIPTION
**Pull request by Valdnet**
1. Changing the style of the sentence.
2. Unifying the sentence with Talk Nextcloud https://github.com/nextcloud/spreed/pull/7790.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by Valdnet** [comment]
@rakekniven Thanks, my oversight 😉.

**Comment by Valdnet** [comment]
@AndyScherzinger Can you backport to version 14.1 and 14.2?

**Comment by AndyScherzinger** [comment]
Likely failed due to the string related to a v15 feature, so not present before thus no backports needed and failing 😉

**Comment by Valdnet** [comment]
Thanks for the clarification 😉.

**Pull request merged**
