### PR TITLE
Refactored Message input view into it's own Fragment

### LINKED ISSUE #3784: Refactor MessageInput logic into it's own fragment
- Related https://github.com/nextcloud/talk-android/pull/3704#issuecomment-1999927317

`MessageInput` has grown in complexity. It's unreasonable to have it in `ChatActivity`. It should be moved into it's own fragment to simplify the logic, and prevent future bugs from occurring.

### PR DESCRIPTION
**Pull request by rapterjet2004**
- fixes #3784 

###  Introduction
Shouldn't be merged until after the stable release.

`MessageInput` is very complex, spanning 1300+ lines of code. It deals with sending, recording, emojis, files, editing, mentioning, etc. It should be placed into it's own fragment, so `ChatActivity` becomes easier to maintain in the long run. Bit of an investment cost though and not necessarily a priority in case other features require attention. But it's something that should be taken care of before it gets out of control. Chatting is the core functionality of talk-android, and needs to be structured well.

This also gives me an opportunity to clean up the architecture of the view. Separate UI from business logic, and deal with asynchronous work in a less "Spaghetti" manner. Less threads, more coroutines. Less logic in the UI, more logic in the model layer, etc

The plan is the separate the voice recording from the typical messaging. To have two different fragments to handle the behavior. A significant amount of code (admittedly my own 😅 ) is involved in the voice recording logic, which can be pretty complicated.  Fragments transaction events will be observed by the `ChatViewModel` and handled.

As a rule of thumb, I'm going for 25/15/60 (view, view model, model) when [implementing logic in MVVM](https://softwareengineering.stackexchange.com/a/438908). Not everything is implemented in MVVM, just the functionality that relate to message input (with the exception of typing status).

### PR Diagram
Arrows and colors represent the flow and scope of information traveling down from user input. 
Nextcloud MessageInput Diagram (6)

### `// TODO normal message input`
- [x] sending messages
- [x] sending attachments
- [x] emoji button
- [x] replying
- [x] editing
- [x] mentioning
- [x] typing status?
- [x] recording

### `// TODO voice message input`
- [x] Abstracting over MediaRecorder (Note to self: Make mediarecorder state livedata and immutable, good design)
- [x] Abstract over MediaPlayer
- [x] Abstract over AudioRecord
- [x] MicInputCloud
- [x] previewing // note pause mediaplayer before seeking and resume after
   - [x] Preview SeekBar
   - [x] pause/Play
- [x] sending preview
- [x] deleting preview
- [x] Implement Audio Focus Request (perhaps make this a manager too?)
    - [x] Media Player ( in ChatActivity )
    - [x] Voice Message preview player
    - [x] Media Recorder
    - [x] MicInput

### `// TODO clean up`
- [x] Delete all the old code 
- [x] Bugs
    - [x] save messageInputView text and cursor state
    - [x] save position and voicemessage on state change in saved ( this is an issue with the lifecycle being recreated )
    - [x] checkShowMessageInputView
    - [x] checkLobbyState
    - [x] onCreateOptionsMenu (used for context???)
    - [x] handleOnBackPressed
    - [x] Make PreviewSeekbar seekable
    - [x] Fix Voice record bugs
    - [x] use upload file from chatView
    - [x] Micinput restart ui
    - [x] If the preview playback is interrupted, the seekbar will not seek on following recordings, might be related to AudioFocusRequest
    - [x] AudioFocus crash, need to handle receiver illegal arg exception

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by mahibi** [comment]
Edit message is broken:
- Original message is not shown
- send and save button shown at the same time
grafik

**Comment by mahibi** [comment]
- [ ] It crashed when opening voice recording:

```
2024-05-06 15:30:29.820 22667-22667 MessageInputFragment com.nextcloud.talk2 D ACTION_UP
2024-05-06 15:30:29.828 22667-22667 ChatViewModel com.nextcloud.talk2 D Recording stopped
2024-05-06 15:30:29.828 22667-22667 InputEventReceiver com.nextcloud.talk2 E Exception dispatching input event.
2024-05-06 15:30:29.829 22667-22667 MessageQueue-JNI com.nextcloud.talk2 E Exception in MessageQueue callback: handleReceiveCallback
2024-05-06 15:30:29.838 22667-22667 MessageQueue-JNI com.nextcloud.talk2 E java.lang.IllegalArgumentException: Receiver not registered: com.nextcloud.talk.chat.data.io.AudioFocusRequestManager$noisyAudioStreamReceiver$1@da4e131
at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1770)
at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1899)
at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:829)
at com.nextcloud.talk.chat.data.io.AudioFocusRequestManager.handleBecomingNoisyBroadcast(AudioFocusRequestManager.kt:103)
at com.nextcloud.talk.chat.data.io.AudioFocusRequestManager.audioFocusRequest(AudioFocusRequestManager.kt:94)
at com.nextcloud.talk.chat.viewmodels.ChatViewModel.stopAudioRecording(ChatViewModel.kt:586)
at com.nextcloud.talk.chat.viewmodels.ChatViewModel.stopAndSendAudioRecording(ChatViewModel.kt:594)
at com.nextcloud.talk.chat.MessageInputFragment.initVoiceRecordButton$lambda$9(MessageInputFragment.kt:359)
```

**Comment by mahibi** [comment]
1. Edit a message and save it
2. Enter permanent voice recording mode
3. Cancel it
Bug: Editing mode is active

**Comment by sowjanyakch** [comment]
1. Edit a message with some extra spaces at the end or don't modify the original message.
2. Send the message. 
3. Edit is performed on the message - bug

**Comment by sowjanyakch** [comment]
1. Type a message in the input message field and rotate the screen.
2. App crashes.

2024-05-08 12:06:50.346 14641-14641 AndroidRuntime com.nextcloud.talk2 E FATAL EXCEPTION: main
Process: com.nextcloud.talk2, PID: 14641
java.lang.NullPointerException
at com.nextcloud.talk.chat.MessageInputFragment.updateOwnTypingStatus$sendStartTypingSignalingMessage(MessageInputFragment.kt:554)
at com.nextcloud.talk.chat.MessageInputFragment.updateOwnTypingStatus(MessageInputFragment.kt:566)
at com.nextcloud.talk.chat.MessageInputFragment$initMessageInputView$1.onTextChanged(MessageInputFragment.kt:203)
at android.widget.TextView.sendOnTextChanged(TextView.java:11785)
at android.widget.TextView.setText(TextView.java:6965)
at android.widget.TextView.setText(TextView.java:6761)
at android.widget.EditText.setText(EditText.java:145)
at android.widget.TextView.setText(TextView.java:6713)
at com.nextcloud.talk.chat.MessageInputFragment.restoreState(MessageInputFragment.kt:157)
at com.nextcloud.talk.chat.MessageInputFragment.onCreateView(MessageInputFragment.kt:125)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8595)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by rapterjet2004** [comment]
It seems the typing indicator is broken in general, unrelated to this PR, but I'm receiving the same error messages that I encountered on Master, so I'm assuming it should be sending the messages at least.

**Comment by mahibi** [comment]
> It seems the typing indicator is broken in general, unrelated to this PR, but I'm receiving the same error messages that I encountered on Master, so I'm assuming it should be sending the messages at least.

As said, typing indicator is broken for now because of https://github.com/nextcloud/spreed/issues/12252
Nothing to fix in your PR...

**Comment by sowjanyakch** [comment]
Looks good to me. One minor modification - let's put the cursor to the end of the message when someone edits a message.

**Comment by mahibi** [comment]
1) type some text
2) wait 30 sec 
3) bug: text disappears

or
1) have some text as draft
2) change text
3) wait 30 sec
4) bug: text is overwritten by old draft

It's kind of expected as https://github.com/nextcloud/talk-android/pull/3918 is not applied because of this PR's changes.
So as mentioned in https://github.com/nextcloud/talk-android/pull/3918#pullrequestreview-2063613411 it would make sense to fix it in better ways..

**Comment by mahibi** [comment]
one minor note: "Slide to cancel" for voice messages is sliding away much faster now

**Comment by rapterjet2004** [comment]
> The chat is not updated anymore (after ~1min ?)

🤦🏾 I forgot to refresh the chat

```diff
is ChatViewModel.GetCapabilitiesUpdateState -> {
                    spreedCapabilities = state.spreedCapabilities
                    chatApiVersion = ApiUtils.getChatApiVersion(spreedCapabilities, intArrayOf(1))
                    participantPermissions = ParticipantPermissions(spreedCapabilities, currentConversation!!)

                    invalidateOptionsMenu()
                    checkShowCallButtons()
                    checkShowMessageInputView()
                    checkLobbyState()
                    updateRoomTimerHandler()
-
+                    chatViewModel.refreshChatParams(
+                      setupFieldsForPullChatMessages(
+                            false,
+                            0,
+                            false
+                        )
+                    )
                }
```

**Comment by mahibi** [comment]
@rapterjet2004 
There is a problem with the session handling caused by onPause and the lifecycle listener.

1) open the chat on phone
2) send a message from web to phone. message is shown correctly
3) while having chat opened, bring the app the background
4) open the app again
5) send another message from web to phone. message is shown as push notification instead to update the chat

This happens because `leaveRoom#onNext` is not executed completely when `onPause` is triggered.
Instead leaveRoom#onNext is triggered when the app is opened again. Inside `leaveRoom#onNext` the websocket session is reset. So the room is not joined at all and that's why the chat not updated but a push notification is received.

**Review by mahibi — CHANGES_REQUESTED** [review]
see overall comments

**Comment by mahibi** [comment]
@rapterjet2004 https://github.com/nextcloud/talk-android/pull/3792#issuecomment-2141996064 is solved right? As the commits are already squashed: can you give a short summary what you changed to solve it?

**Comment by rapterjet2004** [comment]
At first I hardcoded the leave room logic, but the error persisted. After reverting the git, I think the reason for this, is because the bug was caused by my earlier changes to the PR, where I added an additional `GetCapabilitiesUpdateState` so that the message state wouldn't get recreated every time capabilities was called. 

I forgot that when exiting -> entering an activity, the state will still be `GetCapabilitiesUpdateState` instead `GetCapabilitiesInitialLoadState` because it's held in the `ChatViewModel`. Therefore the room would not be joined, and `refreshChatParams` wouldn't be called to the start the recursive chain.

```diff
is ChatViewModel.GetCapabilitiesUpdateState -> {
                    spreedCapabilities = state.spreedCapabilities
                    chatApiVersion = ApiUtils.getChatApiVersion(spreedCapabilities, intArrayOf(1))
                    participantPermissions = ParticipantPermissions(spreedCapabilities, currentConversation!!)

                    invalidateOptionsMenu()
                    checkShowCallButtons()
                    checkShowMessageInputView()
                    checkLobbyState()

+                   if (!validSessionId()) {
+                       joinRoomWithPassword()
+                       chatViewModel.refreshChatParams(
+                           setupFieldsForPullChatMessages(
+                               false,
+                               0,
+                               false
+                           )
+                       )
+                   } else {
+                       Log.d(TAG, "already inConversation. joinRoomWithPassword is skipped")
+                   }
-
                    updateRoomTimerHandler()
}
```

**Comment by mahibi** [comment]
> https://github.com/nextcloud/talk-android/pull/3792#issuecomment-2147501832

But now the situation that GetCapabilitiesUpdateState remains is still the case right? 
Which is confusing because then also GetCapabilitiesUpdateState also contains code for initialization (additionally to the code in GetCapabilitiesInitialLoadState)

I think 

```
+                   if (!validSessionId()) {
+                       joinRoomWithPassword()
+                       chatViewModel.refreshChatParams(
+                           setupFieldsForPullChatMessages(
+                               false,
+                               0,
+                               false
+                           )
+                       )
+                   } else {
+                       Log.d(TAG, "already inConversation. joinRoomWithPassword is skipped")
+                   }
```
should be deleted from 
`is ChatViewModel.GetCapabilitiesUpdateState`
and instead we reset some states in `ChatViewModel#leaveRoom`? E.g.

```
        _getCapabilitiesViewState.value = GetCapabilitiesStartState
        _getRoomViewState.value = GetRoomStartState
```
so the next time the activity is opened the states for initialization are triggered..

**Review by mahibi — APPROVED** [review]

**Pull request merged**
