### PR TITLE
Toolbar/list-item/preferences alignments

### LINKED ISSUE #994: [11 alpha04] Background of file uploading window
Steps:

1. Choose a dark theme.
2. Go to the conversation with the user.
3. Choose to send the file.

The file transfer window background does not turn black for a dark theme.
This makes the font unreadable for the sending function.

obraz

App:
Android 10
Nextcloud Talk 11.0.0 Alpha 04

### LINKED ISSUE #1107: Polish Contacts Screen
The actual contacts screen when creating a new conversation has several different elements that aren't aligned nicely so I put a screenshot of the actual `master` and the default-android-contacts app here.

_Also please ignore the toolbar differences (for now)._

|Nextcloud Talk|Android|
|---|---|
|device-2021-04-08-112816|device-2021-04-08-112852|

### PR DESCRIPTION
**Pull request by AndyScherzinger**
The space between back-arrow and toolbar title has been changed to material's default to make it easier to align list items with the toolbar elements. This has been done for: contacts, user profile and sounds, see screenshots below for examples.

Other than that this PR harmonizes the settings screen layout to not show card views for preference categories and also to use the accent color for category titles  (no actual material design preference screen uses cards and neither is the files app)

|:busts_in_silhouette:Contacts|:sound:Sounds|:gear:Settings|
|---|---|---|
|device-2021-04-08-180536|device-2021-04-08-162546|device-2021-04-09-003103|

Also Fixes #994
Also Fixes #1107

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Don't merge, breaks dark light theme switch 😒

**Comment by AndyScherzinger** [comment]
Theme change issue has been fixed

**Review by jancborchardt — APPROVED** [review]
Good design improvements! :)

(The "play" icon in "Sounds" is a bit much, and could just be a music icon or play triangle? Separate issue though. :)

**Comment by AndyScherzinger** [comment]
> (The "play" icon in "Sounds" is a bit much, and could just be a music icon or play triangle? Separate issue though. :)

@jancborchardt In which way? 

* Just a (grey?) icon, no circular/blue background
* basically how we show music files (without previews) in the Android files client?

**Review by mahibi — APPROVED** [review]

**Comment by mahibi** [comment]
thanks @AndyScherzinger 👌

**Comment by jancborchardt** [comment]
> > (The "play" icon in "Sounds" is a bit much, and could just be a music icon or play triangle? Separate issue though. :)
> 
> @jancborchardt In which way?
> 
>     * Just a (grey?) icon, no circular/blue background
> 
>     * basically how we show music files (without previews) in the Android files client?

Checked how Android does it, and Signal too: They open a modal with a simple list of radio circles, no icons – let’s ideally just do it like that :)
notification sounds

**Pull request merged**
