### PR TITLE
Show conversation search results first

### LINKED ISSUE #2504: Show conversation search results first
### Steps to reproduce

1. Search for a conversation

### Expected behaviour

Most of the time I search for an existing conversation so I'd expect those to be listed first in the search results

### Actual behaviour

However the conversation list loads but then shortly after the message search results get added on top of that, so that it always requires you to scroll down.

I feel like searching for a conversation is the more common use case.

cc @nextcloud/designers 

### Device brand and model

Pixel 3a

### Android version

12

### Nextcloud Talk app version

15.1.0 Alpha 05

### Nextcloud server version

25.0.0 RC 5

### Talk version

15.0.0 RC 5

### Custom Signaling server configured

_No response_

### Custom TURN server configured

_No response_

### Custom STUN server configured

_No response_

### Android logs

_No response_

### Server log

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Fixes #2504

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
getting this into 15.0.2 would be great since many (internal) users would love having it :)

**Review by juliushaertl — APPROVED** [review]
Can't judge on the code but works like a charm ♥️

**Comment by AndyScherzinger** [comment]
Thanks @juliushaertl and also works on my phone :)
The code is easy to judge, it simply calculates the position of the insert as being the end while before it was "0" inserting it at the beginning of the collection

**Review by mahibi — APPROVED** [review]

**Pull request merged**
