### PR TITLE
Use DialogFragment for Phone Number Integration

### PR DESCRIPTION
**Pull request by parneet-guraya**
Fixes: #3737 

### 🖼️ Screenshots

https://github.com/nextcloud/talk-android/assets/111801812/d2f59153-8402-49fd-9eab-94624a3f81c6

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by mahibi** [comment]
Good question from @parneet-guraya copied from public chat:

"Hi 👋 . In some places we are using AlertDialog Builder to show a dialog instead of a DialogFragment. As a result neither they retain state nor they survive configuration changes. I was wondering if we should convert those to use DialogFragment as well?
Or should we keep the simpler ones (yes/no) as is (to avoid creatingseparate files but again they won't survive config change) and convert those which have some state to retain?"

**Comment by mahibi** [comment]
> Good question from @parneet-guraya copied from public chat:
> 
> "Hi 👋 . In some places we are using AlertDialog Builder to show a dialog instead of a DialogFragment. As a result neither they retain state nor they survive configuration changes. I was wondering if we should convert those to use DialogFragment as well? Or should we keep the simpler ones (yes/no) as is (to avoid creatingseparate files but again they won't survive config change) and convert those which have some state to retain?"

I am still undecided. Maybe this behavior could be fixed when switching to more modern solutions like Jetpack Compose etc.?
So maybe it's worth it to keep it like it is until then, instead to create more xml layouts.
Anyone with opinions on this?

**Review by rapterjet2004 — APPROVED** [review]

**Comment by parneet-guraya** [comment]
> I am still undecided. Maybe this behavior could be fixed when switching to more modern solutions like Jetpack Compose etc.? So maybe it's worth it to keep it like it is until then, instead to create more xml layouts. Anyone with opinions on this?

I think we should atleast use DialogFragment for Dialogs those have some state. Otherwise it is bad experience for the user if the dialog loose state for eg. Dialogs with Text fields like this one. It should retain whatever user has typed in. 

let me know your thoughts :-)

**Comment by sowjanyakch** [comment]
@parneet-guraya I agree that it is a bad user experience. 

If there are many AlertDialogs, I prefer to use Jetpack Compose. In Jetpack Compose, we can reuse the composable with custom styles and content. Managing state also becomes easier. 

The approach you are mentioning creates many xml layouts. These files need to be converted to Jetpack Compose eventually.

**Comment by mahibi** [comment]
Lets merge this one as it definitely improves the dialog.
I did not have a look how many other dialogues may be affected. From my side it's not high priority and i would prefer to wait to check this after we migrated to Jetpack Compose.

**Pull request merged**
