### PR TITLE
Allow continuous recording and previewing of voice messages

### LINKED ISSUE #2790: Allow continuous recording of voice messages
Meta ticket at https://github.com/nextcloud/spreed/issues/8819

> I checked Telegram, Signal and Whatsapp and they all have a "slide top to lock in" option.

Maybe we can also add something a like.

### PR DESCRIPTION
**Pull request by rapterjet2004**
fixes #2790 

# Current PR demo
[cont-voice-recording-new.webm](https://github.com/nextcloud/talk-android/assets/69230048/a4f55f4b-70b6-4924-90a8-bdcb4c0f8785)

## 🚧 TODO
- [x] Basic locked, pause/play, delete, send, time keeping functionality
- [x] Ability to preview the current recording while paused
- [x] Finish fancy UI and get Custom component to respond to mic input
- [x] Rebase
- [x] Bug fixes / pause stop/ Review

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by rapterjet2004** [comment]
@mahibi 
@AndyScherzinger 

It's not completely done, as of now I still need to deal with the detekt errors and allow the preview voice recording to be paused/stopped. But for the most part the main functionality is complete.

I could use some help with the theming, I tried to make it functional, but the colors are pretty messed up on light mode and I'm not familiar with the view theme utils. 

Also any thoughts on the UI? I haven't tested it on a physical device yet so I don't know how smooth it feels. Also I feel that the "swipe up to lock" functionality isn't really intuitive, unless the icon is changed to give the user a hint.

**Comment by mahibi** [comment]
well done @rapterjet2004 :+1: 

some remarks from my side:

- [ ] vibration is too long when entering locked mode
- [ ] from my pov the icons are too big. compared to other UI elements they are huge. On the other hand voice recording might be used in scenarios when people can not type very accurately. So could be discussed..
- [ ] in my opinion the pause button should really only pause the recording. Currently the old recording is discarded and a new one is started when clicking the "reload" button.
   - [ ] If pausing the recording is too difficult for now, the pause icon shouldn't be used and maybe should be replaced by a stop icon..?
- [ ] some copyright headers are missing
- [ ] the animation is sometimes cropped
grafik
- [ ] one corner is not rounded
grafik

Just as a side note but no need for action in this PR: quite some code is added to the ChatActivity here. That's okay for now as it was always done like this. In the long term we should try to extract things (via fragments etc).

**Comment by rapterjet2004** [comment]
Yeah @mahibi  is a lot of code in chat activity, after this gets merged, I might made a follow up PR to separate the entire messageInput into its own fragment.

**Comment by AndyScherzinger** [comment]
my time is a bit limited these days to have a deeper look.

From the coloring I would say:

* start/stop button color should match the left/right Button Icons, that ensures the right level of contrast and makes it a "primary" action
* the seekbar seems not been themed at all, you can copy that one from the "outcoming voice message" holder
* click target size should be 48dp in total (including padding)
* icon size of left/right icon should be 24dp
* middle icon could be slightly bigger, overall size should again be 48dp + plus your animation space

Hope it helps 🤞

**Comment by AndyScherzinger** [comment]
@rapterjet2004 could you do a `rebase` on latest master? That would help me with running it.

**Comment by rapterjet2004** [comment]
@AndyScherzinger  Oops, Just realized that the replay preview recording seekBar is messed up on any recording > 5 seconds. I'll see if I can fix that, and knock out some detekt issues while at it.

**Comment by AndyScherzinger** [comment]
@rapterjet2004 I rebased and fixed the lint issue.

Can you make the icon of your `micInput` view smaller?
Screenshot_20230719_122219

see screenshot above. the circle should have a size of `48dp` and the icon inside should be `24dp` and centered, so me it seems the icons are stretched to the size of the view (see refresh icon) and any padding is randomly there based on the padding that is part of the vector itself, but the whole vector needs to be rendered at 24dp in total.

Do you have a way to fix that?
Other than that the theming looks fine so besides this one visual aspect I think it is good to go.

**Comment by rapterjet2004** [comment]
@AndyScherzinger 

image

**Comment by AndyScherzinger** [comment]
Nice polishing @rapterjet2004 🤩

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
