### PR TITLE
Display participants via flexbox layout

### PR DESCRIPTION
**Pull request by AndyScherzinger**
maybe a work in progress but I open the PR just in case so it is on the radar/visible during the time I can't further work on it in case somebody wants to pick up where I paused. :)

Details/documentation for the used flexbox layout: https://github.com/google/flexbox-layout

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@mario seems to be doing what you needed to be done:

device-2017-12-28-172850

device-2017-12-28-172926

Beware though that the flex box (like the linear layout before) has the own camera image (me in this case) hovering above the surface render items...

**Comment by AndyScherzinger** [comment]
btw. I added some spacing via paddings which can just be removed in case you don't want them to be spaced but rather glued together.

**Comment by AndyScherzinger** [comment]
@mario I think we can close this one, right?

**Comment by mario** [comment]
@AndyScherzinger probably :-/ We need to see how to change the layout which is what I'll discuss with you via some kind of video chat or in person. Sorry about that!

**Comment by AndyScherzinger** [comment]
All good @mario :+1: No worries!

**Pull request closed without merging**
