### PR TITLE
Add TURN server documentation

### PR DESCRIPTION
**Pull request by MichaIng**
- Port from help.nextcloud.com as requested: https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/30794/2?u=michaing
- Signed-off-by: Micha Felle <micha.felle@gmx.net>
  - Hope it's okay to stay a bid anonym here 🙂.

### CODE REVIEW

**Comment by mario** [comment]
First of all, thanks for the contribution!

Uh. Unsure if we can accept "anonymous" contributions. Thoughts @schiessle?

**Comment by MichaIng** [comment]
@mario
Hmm, otherwise I might need to switch non-anonymous in github, as Nextcloud is not the only repo that asks for sign-offs :wink:. I just like to stay anonymous in www where I can. I guess full name is required than as well besides real email?

**Comment by mario** [comment]
@MichaIng so what do we do? :)

**Comment by MichaIng** [comment]
@mario @schiessle 
Here you go, edited the sign-off in 1st post 🙂.

**Comment by mario** [comment]
Ha well, the commit isn't properly signed-off :) But I appreciate the contribution and will let it slide this once since you're awesome!

Might make it a bit more generic in the future (so it doesn't reference @mario and @fancycode  in the way it does), plus clarify who wrote this, but yea - YOU ARE AWESOME!

**Comment by MichaIng** [comment]
@mario 
Yeah, at least on github I cannot edit commits any more, once done 🤔. Jep, feel free to adjust it. Let me know if there turns out something about the content wrong, outdated or better "ways" exist. So I can keep the HowTo on help.nextcloud.com up-to-date as well. And of course the other way round. Will properly sign off further commits then 😉.

**Pull request merged**
