### PR TITLE
Load higher resoliton avatars in conversation list (2)

### PR DESCRIPTION
**Pull request by timkrueger**
Supplement to commit 546a174f4.

Resolves: #2302

### CODE REVIEW

**Review by mahibi — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by andyxheli** [comment]
Hi @timkrueger  sorry to bother you! Just updated go 14.2.0 and the avatars still load in low resolution I did a clear cache on the app

**Comment by timkrueger** [comment]
> Hi @timkrueger sorry to bother you! Just updated go 14.2.0 and the avatars still load in low resolution I did a clear cache on the app i see pull request #2305 but that one had issues so i don't see this pull request on this list

No need to sorry. Thanks for the hint. The backport bot were broken and I didn't recognize. It will be in 14.2.1 again.

**Comment by andyxheli** [comment]
Thank you so much!! Have a great rest of your day :)

**Pull request merged**
