### PR TITLE
Add handling for "event.participants.update.all" 

### PR DESCRIPTION
**Pull request by timkrueger**
In case a moderator of a restricted room ends the call for all participants a update participants event with the field 'all=true' will
be thrown by the HPB.

```json
    {
      "type": "event"
      "event": {
        "target": "participants",
        "type": "update",
        "update": [
          "roomid": "the-room-id",
          "incall": new-incall-state,
          "all": true
        ]
      }
    }
```

In that case the call can be ended directly without handling every single participant.

Resolves: https://github.com/nextcloud/talk-android/issues/1881

### CODE REVIEW

**Comment by timkrueger** [comment]
> # SpotBugs increased!

I started fixing that and continue this evening.

**Comment by mahibi** [comment]
tested with sermo which currently supports the "update all" request..
but i have to say with this current state "everything" is broken.. can't establish a successful call, web keeps ringing after hangup, phone keeps ringing 2 times in parallel etc..
we should debug this together i guess.

**Comment by timkrueger** [comment]
> tested with sermo which currently supports the "update all" request.. but i have to say with this current state "everything" is broken.. can't establish a successful call, web keeps ringing after hangup, phone keeps ringing 2 times in parallel etc.. we should debug this together i guess.

🤦 

I added the wrong constant in the [`CallActivity`](https://github.com/nextcloud/talk-android/blob/d05566b67d75742a2be25181847bb65f46f8a3fc/app/src/main/java/com/nextcloud/talk/activities/CallActivity.java#L1488):

```
-            case TARGET_PARTICIPANTS:
+            case PARTICIPANTS_UPDATE:
                 Log.d(TAG, "onMessageEvent 'participantsUpdate'");
```

Can you please try again @mahibi ?

**Comment by mahibi** [comment]
LGTM code wise, didn't test because sermo was not set up with the hpb changes. 
so remember to test it once everything is merged..

**Review by mahibi — APPROVED** [review]

**Comment by mahibi** [comment]
i guess @nickvergessen wants to have this in for 14.0.2 ?

**Comment by AndyScherzinger** [comment]
@timkrueger can you manually backport please?

**Pull request merged**
