### PR TITLE
Add item background for popup menu items

### LINKED ISSUE #1273: Theme for message menus
## Steps to reproduce

1. Set the app's theme to dark.
2. Create a conversation.
3. Write a message.
4. Mark the body of the message.

The background color of the menu does not change to the set theme:

obraz

## Device information

**Android version:** 10

**Talk version:** 12.0.0 Alpha 13

## Server information

**Nextcloud version:** 21.0.1

**Talk version:** 11.2.1

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Fixes #1273

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Successfully tested 👍

**Review by mahibi — APPROVED** [review]

**Pull request merged**
