### PR TITLE
improve voice message quality

### LINKED ISSUE #1613: Poor audio quality of voice messages
## Steps to reproduce
1. Record an audio message

### Expected behaviour
Audio message has similar quality as in Nextcloud Talk web version, whatsapp, telegram, signal etc.

### Actual behaviour
It is very tinny and not at pleasure to hear that voice message at all.

## Device information

**Talk version:** 12.2.1

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 22.1.1

**Talk version:** (see apps admin page: `/index.php/settings/apps`)  12.1.2

### PR DESCRIPTION
**Pull request by mahibi**
resolve #1613

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by nickvergessen** [comment]
Can you send one with this to Ivan, so he can test playing it in Safari and the iOS app?
I remember issues back then

**Comment by mahibi** [comment]
> Can you send one with this to Ivan, so he can test playing it in Safari and the iOS app? I remember issues back then

@Ivansss i sent you a voice message on sermo. could you test and let me know if this works/ how the quality is?

**Comment by Ivansss** [comment]
Sounds good on the iOS app 👍 

But I get an error in Safari 😕 
Screenshot 2023-01-23 at 18 00 38

**Comment by mahibi** [comment]
> Sounds good on the iOS app +1
> 
> But I get an error in Safari 

so we tested and somehow sampling rate 22050 recorded on android works on safari (But it's strange that 44100 won't, because that the value that the iOS app uses and safari can handle these recordings from iOS).

**Review by Ivansss — APPROVED** [review]
Worked in our tests on iOS app and Safari 👍

**Comment by nickvergessen** [comment]
👍🏼

**Comment by mahibi** [comment]
confirmed it also works on edge...

**Pull request merged**
