### PR TITLE
Add support for findBugs, lint

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Additionally I added all "2. to review" PRs to https://www.kaminsky.me/nc-dev/reviews.html, same like on files-library/files repo.

**Comment by AndyScherzinger** [comment]
Can we upgrade to the newer findbugs version(s), like I proposed in this PR: https://github.com/nextcloud/android/pull/2971 ?

**Comment by tobiasKaminsky** [comment]
Done

**Comment by AndyScherzinger** [comment]
Nope, you missed fb-contrib 7.4.2->7.4.3 ;)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky see https://github.com/nextcloud/talk-android/pull/305#issuecomment-419452983 lint went through the roof also detecting one error

**Comment by tobiasKaminsky** [comment]
Yeah, so it is. 
https://drone.nextcloud.com/nextcloud/talk-android/374/12 all pushes to master also have this. (if you directly push to master you do not really see the increase of error/warnings)
My suggestion is to now only use PR and as there Drone is a required check, it should not happen again that lint increases (only on purpose; same like in nextcloud/android).

--> I'll change lint so this turns green.

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mario** [comment]
Thanks for the contribution.

**Pull request merged**
