### PR TITLE
Implemented media/photo share functionality

### LINKED ISSUE #3276: media/photo share function - add to long-press menu
**Summary**

Currently when viewing a photograph that was shared in a Talk conversation - i.e. clicking on the photograph to view full screen - there is a `Share` option under the 3-dot menu.

image

Currently when long-pressing a photograph that was shared in a Talk conversation, the resulting menu _does not_ contain the `Share` function.

Screenshot_20230825-182309_Talk_1

**Describe the solution you'd like**
Would be great to implement the same `Share` function in the long-press menu.
This would offer a simpler workflow: no need to expand a photograph full-screen just to share it.
There is also arguably plenty of screen real-estate to accommodate another function in the long-press menu.

### PR DESCRIPTION
**Pull request by Smarshal21**
Resolves #3276 

*Successfully Implemented media/photo share functionality  on long-pressing a photograph that was shared in a Talk conversation.*
This would offer a simpler workflow: no need to expand a photograph full-screen just to share it.
As there is arguably plenty of screen real-estate to accommodate another function in the long-press menu.

### 🖼️ Screenshots

🏚️ Before
before

🏡 After
after

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by Smarshal21** [comment]
@AndyScherzinger @mahibi  Ptal and let me know the changes 
will create the branches within this repository from the next PR 😀

**Comment by AndyScherzinger** [comment]
@Smarshal21 did you or can you test this for images you opened first by clicking on them (triggers a download of the original image) and for not clicking on the image first but going straight for the long press (only the preview image available) since I expect you'd be sharing a different file then or it might not be working on both scenarios.

**Comment by mahibi** [comment]
> @Smarshal21 did you or can you test this for images you opened first by clicking on them (triggers a download of the original image) and for not clicking on the image first but going straight for the long press (only the preview image available) since I expect you'd be sharing a different file then or it might not be working on both scenarios.

it doesn't work when the file is not downloaded. So it only works for images that were opened (downloaded) before.

To test:

- send some image to the user who is logged in at the talk android app.
- DON'T open this file and share it from context menu (e.g. to some other messenger, e.g. whatsapp)
- whatsapp will complain with "the file type is not supported"
- back in nextcloud talk, open the file and go back
- share it from context menu again
- this time it will work


So there should be checked if the file is already downloaded and if it's not, the download should be triggered. When download is finished, the share method should be triggered.

**Comment by Smarshal21** [comment]
> 

Sure, will take a look at it

**Comment by Smarshal21** [comment]
> > @Smarshal21 did you or can you test this for images you opened first by clicking on them (triggers a download of the original image) and for not clicking on the image first but going straight for the long press (only the preview image available) since I expect you'd be sharing a different file then or it might not be working on both scenarios.
> 
> it doesn't work when the file is not downloaded. So it only works for images that were opened (downloaded) before.
> 
> To test:
> 
> * send some image to the user who is logged in at the talk android app.
> * DON'T open this file and share it from context menu (e.g. to some other messenger, e.g. whatsapp)
> * whatsapp will complain with "the file type is not supported"
> * back in nextcloud talk, open the file and go back
> * share it from context menu again
> * this time it will work
> 
> So there should be checked if the file is already downloaded and if it's not, the download should be triggered. When download is finished, the share method should be triggered.

@mahibi i have changed , could you please let me know if the error is still occurring as i am getting some error in joining a chat from another user (some sort of issue).

**Comment by mahibi** [comment]
the error is still occurring.
There must be logic added to actually download the file first (in the chat, it's only a preview if it was never shown fullscreen). Just have a look how it is done for the playback of voice messages:

```
        adapter?.registerViewClickListener(
            R.id.playPauseBtn
        ) { _, message ->
            val filename = message.selectedIndividualHashMap!!["name"]
            val file = File(context.cacheDir, filename!!)
            if (file.exists()) {
                if (message.isPlayingVoiceMessage) {
                    pausePlayback(message)
                } else {
                    setUpWaveform(message)
                }
            } else {
                Log.d(TAG, "Downloaded to cache")
                downloadFileToCache(message)
            }
        }
```

so for sharing the logic should be similar. If the file exists, just continue the the sharing code. If it doesn't exist yet, start the download. When download is finished, come back the share logic. 
In the downloadFileToCache method, you will find 

```
        WorkManager.getInstance(context).getWorkInfoByIdLiveData(downloadWorker.id)
            .observeForever { workInfo: WorkInfo ->
                if (workInfo.state == WorkInfo.State.SUCCEEDED) {
                    setUpWaveform(message)
                }
            }
```

There should be added a condition to check what was downloaded and then continue with the voice playback or the sharing code.

Just let me know if you have more questions. 
Or if you don't find the time just let me know if i should take over.


> as i am getting some error in joining a chat from another user (some sort of issue)
What is this error? if it's not related to the feature just ping me 1:1 in chat

**Comment by Smarshal21** [comment]
> the error is still occurring. There must be logic added to actually download the file first (in the chat, it's only a preview if it was never shown fullscreen). Just have a look how it is done for the playback of voice messages:
> 
> ```
>         adapter?.registerViewClickListener(
>             R.id.playPauseBtn
>         ) { _, message ->
>             val filename = message.selectedIndividualHashMap!!["name"]
>             val file = File(context.cacheDir, filename!!)
>             if (file.exists()) {
>                 if (message.isPlayingVoiceMessage) {
>                     pausePlayback(message)
>                 } else {
>                     setUpWaveform(message)
>                 }
>             } else {
>                 Log.d(TAG, "Downloaded to cache")
>                 downloadFileToCache(message)
>             }
>         }
> ```
> 
> so for sharing the logic should be similar. If the file exists, just continue the the sharing code. If it doesn't exist yet, start the download. When download is finished, come back the share logic. In the downloadFileToCache method, you will find
> 
> ```
>         WorkManager.getInstance(context).getWorkInfoByIdLiveData(downloadWorker.id)
>             .observeForever { workInfo: WorkInfo ->
>                 if (workInfo.state == WorkInfo.State.SUCCEEDED) {
>                     setUpWaveform(message)
>                 }
>             }
> ```
> 
> There should be added a condition to check what was downloaded and then continue with the voice playback or the sharing code.
> 
> Just let me know if you have more questions. Or if you don't find the time just let me know if i should take over.
> 
> > as i am getting some error in joining a chat from another user (some sort of issue)
> > What is this error? if it's not related to the feature just ping me 1:1 in chat

Sure 
Yeah i will solve this issue

**Comment by Smarshal21** [comment]
@mahibi @AndyScherzinger ptal i have updated and it works for me

**Comment by mahibi** [comment]
> @mahibi @AndyScherzinger ptal i have updated and it works for me

reviewing.. i will commit some suggested changes soon

**Comment by mahibi** [comment]
> @mahibi @AndyScherzinger ptal i have updated and it works for me

i commited some suggested changes, see commit message of abb33893089dd5a88361e595c3dfec879bcfbf7e

**Comment by Smarshal21** [comment]
> > @mahibi @AndyScherzinger ptal i have updated and it works for me
> 
> i commited some suggested changes, see commit message of [abb3389](https://github.com/nextcloud/talk-android/commit/abb33893089dd5a88361e595c3dfec879bcfbf7e)

is there anything to be implemented ?

**Review by mahibi — APPROVED** [review]

**Pull request merged**
