### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small and useless PR adds two buttons to get your app on F-Droid and Google Play 👍

### CODE REVIEW

**Comment by mario** [comment]
Awesome! One question though: Why is the start of the Gplay button not aligned with the text above and below?

**Comment by mario** [comment]
@Poussinou poke! :)

**Comment by Poussinou** [comment]
Sorry I was off for some days xD I don't really know, it's allays like that, as you can see [here](https://github.com/nextcloud/android/blob/master/README.md) or [here](https://github.com/LawnchairLauncher/Lawnchair/blob/alpha/README.md) for example...

**Comment by mario** [comment]
Thanks, you're awesome!

**Pull request merged**
