### PR TITLE
File util fixes

### PR DESCRIPTION
**Pull request by mahibi**
### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Review by tobiasKaminsky — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by firmianay** [comment]
@mahibi Hello, I saw this path traversal vulnerability and its fix. It seems to be a little problematic, because getCanonicalPath returns a path string that is not terminated with a slash, which means that external input may still be copied to siblings 
 of cacheDir, rather than just its children, such as "data/data/package/cachexxxx"
https://codeql.github.com/codeql-query-help/java/java-partial-path-traversal/

**Comment by nickvergessen** [comment]
hi @firmianay please use our security/bugbounty program at https://hackerone.com/nextcloud/ to report related issues.
We are tracking the matter now already, but would be cool for future issues.

**Comment by firmianay** [comment]
Thanks for the reply. I am registering a hackerone account. If you think it is necessary, I can create this issue on it.

**Comment by mahibi** [comment]
as nickvergessen mentioned it's already tracked now but for future security issues just create an issue there. Thanks for your help :+1:

**Pull request merged**
