### PR TITLE
✉️ & ⭕ Allow to add emails and circles as particpants

### PR DESCRIPTION
**Pull request by nickvergessen**
1. Start a conversation
2. Go to conversation info
3. Tab "Add participant"
4. Search for an email address or circle
5. Select it and confirm with "Done"
6. Email is invited to the conversation

Closing another checkbox in the iOS <=> Android comparison

### CODE REVIEW

**Comment by nickvergessen** [comment]
Rebased to fix the conflict with #1246

**Comment by nickvergessen** [comment]
Can't figure out what the last Spotbugs that is new should be about. Giving up.

**Comment by mahibi** [comment]
> Can't figure out what the last Spotbugs that is new should be about. Giving up.

according to spotbugs it should be done with

                            } catch (RuntimeException e) {
                                throw e;
                            } catch (Exception e) {
                                Log.e(TAG, "Parsing response body failed while getting contacts");
                            }

for ContactsController.java:[line 567] ?

**Review by mahibi — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
I'll look into the spotbugs issue :)

**Comment by AndyScherzinger** [comment]
Fix to be pushed right after the phone deployment... the issue is slightly different to solve. The only non-runtime exception that is actually thrown and enforced the try-catch it an `IOException` so this one needs to be caught :)

I'll take care of push, CI green and will merge afterwards 👍

**Review by AndyScherzinger — APPROVED** [review]
LGTM, merge will break `stable-11` branch since the removal of one string source (by this PR) will then be propagated to this master and stable* branches while `stable-11` is still using this string. Only proper fix for the moment will be to add the string source merge logic present for the files app repo also for the talk app repo...

**Comment by AndyScherzinger** [comment]
String merge PR https://github.com/nextcloud/docker-ci/pull/280

**Pull request merged**
