### PR TITLE
Bug fixes for offline support

### PR DESCRIPTION
**Pull request by rapterjet2004**
- [x] Fix duplicate messages
- [x] Fix duplicate conversations
- [x] Fix crashes on empty conversations
- [x] Unable to Join open conversations
- [ ] ~Fix Unread messages not showing up correctly when entering a conversation~ see https://github.com/nextcloud/talk-android/pull/4069#pullrequestreview-2277339509
- [x] Delete all messages sometimes stops the UI from updating. Might be an issue with initMessagePolling

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by rapterjet2004** [comment]
See

https://github.com/nextcloud/talk-android/pull/3952#issuecomment-2278202226
https://github.com/nextcloud/talk-android/pull/3952#issuecomment-2278226879

**Comment by niclasheinz** [comment]
I would like to add the following to this comment https://github.com/nextcloud/talk-android/pull/3952#issuecomment-2284307047:

- Storage Manager: 
  Here you can set after how many weeks/months/years the chat messages/media files are automatically deleted locally. 

- Global settings:
 - Activate/deactivate offline support
 - Decide what is made available offline:
    - Messages
    - Media files such as images Documents
    - audios
    - surveys
    - Locations
    - Contacts

The same settings can be overwritten or adjusted in the individual chats.

**Comment by AndyScherzinger** [comment]
@rapterjet2004 Also broken atm is scrolling to the oldest unread message when entering a talk room with unread messages. Currently it simply renders right at the end of the conversation.

**Review by mahibi — CHANGES_REQUESTED** [review]
There is a difference between lastReadMessage and lastCommonRead. The code in this PR mixes these things which creates new bugs. @rapterjet2004 Would you mind to revert everything to "Fix Unread messages not showing up correctly when entering a conversation" and i will fix it in a separate PR?

**Comment by mahibi** [comment]
> I would like to add the following to this comment [#3952 (comment)](https://github.com/nextcloud/talk-android/pull/3952#issuecomment-2284307047):
> 
>     * Storage Manager:
>       Here you can set after how many weeks/months/years the chat messages/media files are automatically deleted locally.
> 
>     * Global settings:
>       
>       * Activate/deactivate offline support
>       * Decide what is made available offline:
>         
>         * Messages
>         * Media files such as images Documents
>         * audios
>         * surveys
>         * Locations
>         * Contacts
> 
> 
> The same settings can be overwritten or adjusted in the individual chats.

Thank you for the ideas @niclasheinz , some of them may be implemented in the future.

**Review by mahibi — APPROVED** [review]

**Pull request merged**
