### PR TITLE
Fix #54 - resized launcher logo

### LINKED ISSUE #54: Logo in new icon is too small
The main round form in the logo is significantly smaller than in the previous Talk app.

I'm a bit confused why since in the source file I only modified the background size and opacity.

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Fix #54

Foreground-Logo size is 83% in this PR
2018-01-17 14_08_43-asset studio

### CODE REVIEW

**Comment by mario** [comment]
Hm 80% looks significantly more elegant to me.

**Comment by AndyScherzinger** [comment]
Changed it to 80% (remark: I am using the files in drawable_resources for the generator) and there isn't a real difference to 83%... (I know yours is/was smaller but I guess you used different source assets):
2018-01-17 14_17_23-asset studio

**Comment by AndyScherzinger** [comment]
The diff tab shows the difference and I'll leave it up to you and @jancborchardt.

Just here to help 😺

**Comment by mario** [comment]
This is already too big, so I'll merge :P

**Comment by jancborchardt** [comment]
I'd have gone with the 83% since on square it looks really tiny still, no?

**Comment by mario** [comment]
Noooo, please :D

**Pull request merged**
