### PR TITLE
use MVVM for Geocoding

### PR DESCRIPTION
**Pull request by Smarshal21**
**Implemented LiveData for GeoLocation RecyclerView**

https://github.com/nextcloud/talk-android/assets/99678760/0e772e34-5f77-4253-8f2e-40e8b90b5e84

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by Smarshal21** [comment]
@AndyScherzinger PTAL and suggest me the changes 
Excuse me for my poor internet connection 😅😅

**Comment by mahibi** [comment]
there are still the methods
`searchLocation()`
and
`executeGeocodingRequest()`
in the GeocodingActivity and they are still used by `onResume()`

remove these 2 methods and take the viewModel for it.

As it's not necessary to trigger the geocoding on screen rotation in onResume (viewModel will survive..), maybe there should be some check to only do this when the adapter has no items. So it should only happen initially when the query is passed from LocationPickerActivity. 

As 
`query = intent.getStringExtra(BundleKeys.KEY_GEOCODING_QUERY)`
is always set again in onCreate in GeocodingActivity, this can lead to a bug when rotating the screen. 
After searching for other queries, you would still set the old query that was initially passed to GeocodingActivity after rotating the screen.
Lets try to initially set the query that was passed to GeocodingActivity into the viewModel. Then forget about the bundleKey or ignore it whenever the query is already set inside the viewModel.
And where ever you need to get the query, get it from the viewModel, for example in onCreateOptionsMenu.

**Comment by Smarshal21** [comment]
> there are still the methods `searchLocation()` and `executeGeocodingRequest()` in the GeocodingActivity and they are still used by `onResume()`
> 
> remove these 2 methods and take the viewModel for it.
> 
> As it's not necessary to trigger the geocoding on screen rotation in onResume (viewModel will survive..), maybe there should be some check to only do this when the adapter has no items. So it should only happen initially when the query is passed from LocationPickerActivity.
> 
> As `query = intent.getStringExtra(BundleKeys.KEY_GEOCODING_QUERY)` is always set again in onCreate in GeocodingActivity, this can lead to a bug when rotating the screen. After searching for other queries, you would still set the old query that was initially passed to GeocodingActivity after rotating the screen. Lets try to initially set the query that was passed to GeocodingActivity into the viewModel. Then forget about the bundleKey or ignore it whenever the query is already set inside the viewModel. And where ever you need to get the query, get it from the viewModel, for example in onCreateOptionsMenu.

Done 👍🏻
PTAL and suggest me the changes

**Comment by mahibi** [comment]
@Smarshal21 i pushed some changes, hope that's okay for you.
e.g. to avoid using instanceState, as this can be handled by the view model.
If you have any questions regarding my commit just let me know.

**Comment by Smarshal21** [comment]
> @Smarshal21 i pushed some changes, hope that's okay for you. e.g. to avoid using instanceState, as this can be handled by the view model. If you have any questions regarding my commit just let me know.

yeah i got 
Its fine

**Review by rapterjet2004 — APPROVED** [review]

**Pull request merged**
