### PR TITLE
Remove EntryMenuController and OperationMenuController

### PR DESCRIPTION
**Pull request by mahibi**
This PR removes EntryMenuController and OperationMenuController, see https://github.com/nextcloud/talk-android/issues/1551.
Remaining controllers are now "only" the ones related to the login process.

The "operation view" at the bottom is replaced by snackbars.

One thing worth mentioning:
I have removed the join via public link feature for now. This was buggy, complex and incomplete.
This feature must be reimplemented in a more useful place (login screen, so you can use it as a guest without using an existing instance, see https://github.com/nextcloud/talk-android/issues/261).

## Screenshots

UI changes were not the main goal of this PR, but for the sake of completeness here's what's changed UI-wise.

The actions can be triggered via the long click menu in the conversations screen (and Create conversation via Contacts screen)

### before

any successful action | rename conversation | create conversation
------- | -------- | -------- 
grafik | grafik | grafik

## after

added to favorites | removed from favorites 
------- | -------- 
grafik | grafik

marked as unread | marked as read 
------- | -------- 
grafik | grafik 

rename conversation | create conversation (via Contacts screen) | Delete conversation
------- | -------- | -------- 
grafik | grafik | grafik

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
rename conversation | create conversation (via Contacts screen) | Delete conversation
------- | -------- | -------- 
grafik <br/>Let's rename the title to "Rename conversation" and add the label "Conversation name" back to the input field (for A11Y reasons)| grafik <br/>Let's rename the title to "Create conversation" and add the label "Conversation name" back to the input field (for A11Y reasons)| grafik

**Comment by AndyScherzinger** [comment]
added to favorites | removed from favorites 
------- | -------- 
grafik | grafik

Fine for now, for a future version let's shorten the text by removing the conversation name but adding an UNDO action - like GMail does for delete/archive

**Review by AndyScherzinger — CHANGES_REQUESTED** [review]
Conversation Input field as well as dialog buttons aren't themed according to server-provided color but always blue

**Comment by mahibi** [comment]
@AndyScherzinger 
done with your suggested changes.
can you approve the PR?

**Pull request merged**
