### PR TITLE
🕰️Localize time formatting

### LINKED ISSUE #2369: Ability to change time from 24 hour to 12 hour
Is there a way to change the time in the app from 24 hours to 12 hours? Maybe have the app detect that way its setup on the phone so then it can also show under the Talk app. as of right now it runs on 24 hour time. Most of users in the US run on 12 hour time and some people cant read 24 hour time.

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Signed-off-by: jld3103 <jld3103yt@gmail.com>

successor of #2451 to move it to this repo now also supports chat messages
Resolves #2369

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
before | after

### 🚧 TODO

- [ ] review'n'merge

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Feel free to test-drive @andyxheli https://github.com/nextcloud/talk-android/pull/2622#issuecomment-1344532946

**Comment by andyxheli** [comment]
Thank you @AndyScherzinger getting below error when trying to install. There was a problem parsing package

**Comment by andyxheli** [comment]
Sorry! about that Here you go 

image

**Comment by AndyScherzinger** [comment]
Will have to wait for next week, to get in touch with the person administrating the server

**Comment by AndyScherzinger** [comment]
@andyxheli see apk at https://github.com/nextcloud/talk-android/pull/2622#issuecomment-1350735075 - should work

**Review by timkrueger — APPROVED** [review]
LGTM

I did not merge to wait for a response from @andyxheli .

**Comment by andyxheli** [comment]
Just tested @AndyScherzinger @timkrueger and it looks good thank you for implementing this 😊

**Comment by andyxheli** [comment]
Only thing I noticed is that the time for the call activity still show in 24 hour format

**Comment by AndyScherzinger** [comment]
> Only thing I noticed is that the time for the call activity still show in 24 hour format

Do you have a screenshot for that? I did not touch the call activity which would explain that 😄

**Comment by andyxheli** [comment]
Here you go @AndyScherzinger 
image

**Comment by AndyScherzinger** [comment]
Thanks for the testing and feedback, also fixed the system messages now 👍

**Pull request merged**
