### PR TITLE
Rebase action: /rebase as comment

### PR DESCRIPTION
**Pull request by AndyScherzinger**
shameless c&p from https://github.com/nextcloud/android/pull/8488 where it has been shamelessly copied from the desktop repo ;)

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Review by mahibi — APPROVED** [review]

**Comment by szaimen** [comment]
cc @skjnldsv maybe this could be something for the server repository, too?

**Comment by AndyScherzinger** [comment]
@szaimen @skjnldsv it then be nice if somebody could take a look into https://github.com/nextcloud/android/pull/8488/files#r640384338 and upgrade the GH action to use the latest version. Being lazy I just c&p-ed it while mentioning that it should be updated at some point.

**Comment by skjnldsv** [comment]
Damn, yeah!
But those github actions are getting complicated to maintain.
We really need a template repo and a script to copy/update some basics (like fixup check, node, etc etc)

I guess the script would create a PR updating the file if there is a new update from the template repo and the filename matches? :thinking: 

i'm sure other would love it

**Comment by AndyScherzinger** [comment]
And on the template repo we could run an updater action like: https://github.com/marketplace/actions/github-actions-version-updater

**Pull request merged**
