### PR TITLE
Hide shared items toolbar on scroll

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Comment by timkrueger** [comment]
@AndyScherzinger  Is this for UI behavior alignment with Android Files? 

Currently also if you're scrolling in a conversation the app bar is always visible.

Personally I prefer it to have the app bar available all the time. 

@mahibi What your opinion?

**Comment by mahibi** [comment]
i also prefer to hide the toolbar

> Currently also if you're scrolling in a conversation the app bar is always visible.

that's an exception that is okay for chat apps i would say..

**Review by mahibi — APPROVED** [review]

**Comment by timkrueger** [comment]
OK. Then I'm fine with that 😃

**Review by timkrueger — APPROVED** [review]

**Pull request merged**
