### PR TITLE
🎨 Server theming

### LINKED ISSUE #250: 🎨 Support Server theme
As a company owner I would like to have the theme configured at the server visible in the mobile app.

Maybe related to #207

### PR DESCRIPTION
**Pull request by AlvaroBrey**
Fixes #250 

- [x] fix crash on initial, clean app launch when no user exists
- [x] fallback to xml provided colors in case no theme information from server available
- [x] ~~grey theming for settings dialogs radio buttons (see files app for reference)~~ Do this _after_ moving SettingsController to an Activity implementation

Chat controller WIP:
- [x] Send button
- [x] Outgoing messages
   - [x] Normal outgoing messages
   - [x] File icons (folder and archive)
   - [x] Audio
   - [x] location links in outgoing shared locations
   
- [x] **CREATE `stable-14.2` BEFORE MERGING TO `master`**

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]
Nice work @AlvaroBrey 👍

**Comment by AndyScherzinger** [comment]
Follow-up issue for improvements is #2255

**Comment by AndyScherzinger** [comment]
👍 fine by me of course and heavily tested/in use via #2084 work

@nickvergessen @jancborchardt what do you think? If we merge it we would ship it with 14.2.0 in August while with 15.0.0 we would enhance/replace it with #2084 bringing a Material 3 implementation of theming, so the UI changes twice in a short timeframe. I'd be fine with it since theming is already in place for iOS, so you can consider this one feature-parity, while Material 3 will then just the the next evolutionary step on top and comes in a relatively short timeframe after but that shouldn't be an issue.

**Review by timkrueger — APPROVED** [review]
I tested on all my devices and in the emulator. 

Very nice work @AlvaroBrey and @AndyScherzinger . Also the nice little improvements here and there :heart_eyes:

**Comment by timkrueger** [comment]
stable-14.2 is created.

I don´t merge this because the drone job is still running. Requested an abort.

**Pull request merged**
