### PR TITLE
Revert AGP 7.2.0 -> 7.1.3

### PR DESCRIPTION
**Pull request by AndyScherzinger**
This reverts commit d3827aac9fa4d0a3b05dfd90ba5d5adc9272ef2b.

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
@AndyScherzinger should you also bump back gradle distribution from 7.4.2 -> 7.3.3?

**Comment by AndyScherzinger** [comment]
@AlvaroBrey I hope not, but let's see, I also migrated stuff in the build script so I might have to revert even more 😭 But let's see if @timkrueger actually has a fix for the CI, then we could keep it 🤞

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey I hope not, but let's see, I also migrated stuff in the build script so I might have to revert even more sob But let's see if @timkrueger actually has a fix for the CI, then we could keep it crossed_fingers

I think the build script migrations are still ok for 7.1.3, since we already did them on Files, and Files is still in 7.1.3. Still, let's wait and see

**Comment by AndyScherzinger** [comment]
obsolete

**Pull request closed without merging**
