### PR TITLE
Fix branch detection for drone PRs

### PR DESCRIPTION
**Pull request by nickvergessen**
Partly reverting #2165 

* When the code summary is reduced, the merged drone state was pushed to `$BRANCH`
* Since #2165 that variable is always master or stable-
* https://drone.nextcloud.com/nextcloud/talk-android/4879/4/2 see lines 605
```
[master a7a56a64] Drone: update Lint results to reflect reduced error/warning count [skip ci]
1 file changed, 1 insertion(+), 1 deletion(-)
To https://github.com/******/talk-android
   fa91ba46..a7a56a64  HEAD -&gt; master
```
* As per "commit" the branch is `master` (first wird in square bracket)
* and was then pushed to master

### CODE REVIEW

**Comment by nickvergessen** [comment]
Failing because 
```
      GIT_USERNAME:
        from_secret: GIT_USERNAME
      GIT_TOKEN:
        from_secret: GIT_TOKEN
```
is not defined anymore?

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
> Failing because
> 
> ```
>       GIT_USERNAME:
>         from_secret: GIT_USERNAME
>       GIT_TOKEN:
>         from_secret: GIT_TOKEN
> ```
> 
> is not defined anymore? Or is that from Drone?

That's in Drone (or should be).

```
running FindBugs...
found warnings: 141
previous warnings: 140
FAIL: warning count increased
```
This means spotbugs has increased since the previous PR was merged. Let me push an update to the spotbugs file

**Review by timkrueger — APPROVED** [review]

**Comment by nickvergessen** [comment]
Doesnt seem it was backported there at all :D

**Pull request merged**
